/// 국가별 앱 문자열 (US=영어, KR=한국어, CN=중국어, JP=일본어)
class AppStrings {
  AppStrings(this.country) : _map = _strings[country] ?? _strings['us']!;

  final String country;
  final Map<String, String> _map;

  static const _strings = {
    'us': {
      'searchHint': 'Search for anything',
      'login': 'Log in',
      'profile': 'Profile',
      'logout': 'Log out',
      'logoutSuccess': 'Logged out successfully',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'themeSystem': 'System',
      'notificationSettings': 'Notifications',
      'privacyPolicy': 'Privacy',
      'helpCenter': 'Help',
      'myPosts': 'Posts',
      'myPostBadge': 'my',
      'myReviews': 'My reviews',
      'myReviewsEmptyTitle': 'No reviews yet',
      'myReviewsEmptyHint': 'Open a drama and write a review in the Reviews tab.',
      'myReviewsSortTitle': 'Sort',
      'myReviewsSortNewest': 'Newest first',
      'myReviewsSortOldest': 'Oldest first',
      'saved': 'Saved',
      'likes': 'Likes',
      'tabLikedPosts': 'Posts',
      'tabLikedReviews': 'Reviews',
      'likesEmptyPosts': 'No liked posts yet.',
      'likesEmptyReviews': 'No liked reviews yet.',
      'likesEmptyComments': 'No liked comments yet.',
      'likesLoginRequired': 'Sign in to see posts, reviews, and comments you liked.',
      'recentActivity': 'RECENT ACTIVITY',
      'moreActivity': 'More activity',
      'profileRecentActivityEmpty': 'No rated dramas yet. Rate a drama to see it here.',
      'diary': 'Diary',
      'diaryTitleWithName': "{name}'s Diary",
      /// 닉네임·표시 이름·이메일 앞부분을 모두 알 수 없을 때 (영어 소유격 회피).
      'diaryTitleWhenAnonymous': 'My Diary',
      'diaryEmpty': 'No diary entries yet. Watch dramas from Shorts to fill your diary.',
      'tabLists': 'Lists',
      'listsTitleWithName': "{name}'s Lists",
      'listsFilmCount': '{n}',
      'listsCustomHint': 'More lists you create will show here in a future update.',
      'listsWatchlistDescription':
          'Dramas you saved with Want to watch. Tap to open the full poster grid.',
      'listsFilterSoon': 'List filters are coming in a future update.',
      'listCreateButton': 'Create list',
      'listCreateSuccess': 'List created.',
      'listCreateTitle': 'Create list',
      'listCreateFieldTitle': 'title',
      'listCreateFieldTitleHint': 'e.g. Best revenge thrillers',
      'listCreateFieldDescription': 'description',
      'listCreateFieldDescriptionHint': 'Describe what this list is about.',
      'listCreateDramaCount': 'Dramas ({count}/{max})',
      'listCreateAddDrama': 'Add drama',
      'listCreateNoDramaYet': 'No dramas added yet.',
      'listCreateSubmit': 'Create list',
      'listCreateSubmitting': 'Creating...',
      'listCreateErrorNeedTitle': 'Please enter a title (at least one character).',
      'listCreateErrorNeedDrama': 'Please add at least one drama.',
      'listCreateDuplicateDialogTitle': 'Already added',
      'listCreateErrorDuplicateDrama': 'This drama is already added.',
      'listCreateErrorMaxDrama': 'You can add up to 20 dramas.',
      'listCreateLoginRequired': 'Sign in to create a list.',
      'listCreateErrorSaveFailed': 'Could not save the list. Try again.',
      'listDetailScreenTitle': 'List',
      'listEditTitle': 'Edit list',
      'listEditSave': 'Save',
      'listDeleteConfirmTitle': 'Delete this list?',
      'listDeleteConfirmMessage':
          'This cannot be undone. The list will be removed from your profile.',
      'listDetailDeleteFailed': 'Could not delete the list. Try again.',
      'listDetailEmptyGrid': 'No dramas in this list yet.',
      'listDetailLikePrompt': 'LIKE?',
      'listDetailLikesSingular': '{n} like',
      'listDetailLikesPlural': '{n} likes',
      'listCreateCoverTitle': 'List cover (optional)',
      'listCreateCoverHint':
          'Shown only at the top of this list page. Use gallery (+) to pick an image and crop (2:3). Choose None to clear.',
      'listCreateCoverNone': 'None',
      'listCreateCoverGalleryPickFailed': 'Could not open the gallery or read the image.',
      'listCreateCoverUploadFailed': 'Could not upload the cover image. Try again.',
      'listCreateCoverCropTitle': 'Adjust cover',
      'listCreateCoverImageLoadFailed': 'Could not load this image for cropping.',
      'listMultiPickApply': 'Add ({n})',
      'listMultiPickStepLimit': 'You can select up to {n} dramas on this screen.',
      'tabWatchlist': 'Watchlist',
      'watchlistTitleWithName': "{name}'s Watchlist",
      'likesTitleWithName': "{name}'s Likes",
      'tabSavedPosts': 'Saved posts',
      'watchlistEmptyTitle': 'Nothing on your Watchlist yet',
      'watchlistEmptyPublic': 'Nothing here yet',
      'watchlistRemoveTitle': 'Remove from Watchlist?',
      'watchlistRemoveMessage': 'This title will be removed from your Watchlist.',
      'dramaWatchlistAdd': 'Want to watch',
      'dramaWatchlistRemove': 'On Watchlist',
      'watchlistToastAdded': 'Added to your Watchlist.',
      'watchlistToastRemoved': 'Removed from Watchlist.',
      'watchlistLoginRequired': 'Sign in to use your Watchlist.',
      'dramaWatchHistoryTooltipAdd': 'Mark as watched',
      'dramaWatchHistoryTooltipRemove': 'Remove from watch history',
      'watchHistoryToastAdded': 'Added to your watch history.',
      'watchHistoryToastRemoved': 'Removed from watch history.',
      'dramaSubpageConfirmWatchTitle': 'Add to watch history?',
      'dramaSubpageConfirmWatchBody':
          'This drama will show as watched in your Diary.',
      'dramaSubpageConfirmWatchAlready': 'This drama is already in your watch history.',
      'dramaSubpageConfirmWatchlistTitle': 'Add to Watchlist?',
      'dramaSubpageConfirmWatchlistBody':
          'This drama will appear on your Profile Watchlist.',
      'dramaSubpageConfirmWatchlistAlready':
          'This drama is already on your Watchlist.',
      'dramaWatchlistSubpageBodyOn':
          'This drama is on your Profile Watchlist.',
      'dramaWatchlistSubpageBodyOff':
          'Tap + above to add it to your Watchlist.',
      'dramaWatchActivitySheetTitle': 'Log your watch',
      'dramaWatchActivityWatchLabel': 'Watched',
      'dramaWatchActivityOptionalStars': 'Rating (optional)',
      'dramaWatchActivityReviewHint':
          'Review (optional — select a rating first)',
      'dramaWatchActivityPosted': 'Posted to the feed.',
      'dramaWatchActivityLoginRequired': 'Sign in to post.',
      'dramaWatchActivityWatchOrdinal1': 'First-time watch',
      'dramaWatchActivityWatchOrdinal2': 'Second watch',
      'dramaWatchActivityWatchOrdinal3': 'Third watch',
      'dramaWatchActivityWatchOrdinalN': 'Watch {n}',
      'dramaWatchActivityHeaderRating': 'Rating',
      'dramaWatchActivityHeaderReview': 'Review',
      'dramaBottomActionWatch': 'Watch',
      'dramaBottomActionRate': 'Rate',
      'dramaBottomActionReview': 'Review',
      'dramaBottomActionWatchlist': 'Watchlist',
      'statsBarWatchersLabel': 'Watch',
      'statsBarReviewsLabel': 'Reviews',
      'statsBarListsLabel': 'Lists',
      'statsBarFirstWatcher': 'Watch',
      'statsBarWriteReview': 'Reviews',
      'statsBarMakeList': 'List',
      'statsBarComingSoon': 'Coming soon',
      'dramaReviewsTabPopular': 'Popular',
      'dramaReviewsTabAll': 'All',
      'dramaListsEmptyFeed': 'Load the drama catalog to preview lists here.',
      'tagDramaListEmpty': 'No dramas in the catalog match this tag yet.',
      'savedPostsEmptyTitle': 'No saved posts yet',
      'savedPostsEmptyHint': 'Save a post from the community with the bookmark icon.',
      'home': 'Home',
      'shorts': 'Shorts',
      'popular': 'Popular',
      'freeBoard': 'TALK',
      'questionBoard': 'Ask',
      'welcomeLogin': 'Welcome to DramaHub',
      'loginSubtitle': 'Enter your email and password',
      'email': 'Email',
      'password': 'Password',
      'signUp': 'Sign up',
      'noAccount': "Don't have an account? ",
      'hasAccount': 'Already have an account? ',
      'welcomeSignup': 'Start connecting\nwith DramaHub',
      'signupSubtitle': 'The app will display in this language. Your posts will only be visible to users who selected the same language.',
      'country': 'Country',
      'nickname': 'Nickname',
      'nicknameHint': 'Name shown to other users',
      'passwordConfirm': 'Confirm password',
      'signUpButton': 'Sign up',
      'popularPlaceholder': 'Popular',
      'freeBoardPlaceholder': 'TALK',
      'tabHot': 'Trend',
      'tabGeneral': 'Talk',
      'tabQnA': 'Ask',
      'talkAskFeedLayoutSwitchToCards': 'Card layout',
      'talkAskFeedLayoutSwitchToList': 'List layout',
      'tabReviews': 'Reviews',
      'trendTabHint': 'Posts with 10+ likes or 100+ views appear here.',
      'reviewsTabEmpty': 'Search a drama and post the first review.',
      'spoilerBadge': 'Spoilers',
      'reviewSpoilerDisclaimer': 'Review may contain spoilers.',
      'reviewSpoilerTapToRevealLetterboxd': 'This review may contain spoilers. Tap to reveal.',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'letterboxdReviewDetailTabReview': 'Review',
      'letterboxdReviewDetailTabPostWithCount': 'Comments {n}',
      'letterboxdReviewDetailAppBarTitle': "{name}'s Review",
      'letterboxdReviewWatchedLine': 'Watched {date}',
      'selectDrama': 'Search drama',
      'reviewDramaSearchHint': 'Search short drama',
      'ratingLabel': 'Rating',
      'spoilerToggle': 'Contains spoilers',
      'reviewNeedDramaRating': 'Choose a drama and a star rating to post a review.',
      'reviewNeedDrama': 'Please select a drama for your review.',
      'reviewPleaseSelectRating': 'Please select a star rating.',
      'search': 'Search',
      'searchScopeTitleAndBody': 'Title+Content',
      'searchScopeTitle': 'Title',
      'searchScopeBody': 'Content',
      'searchScopeComment': 'Comment',
      'searchScopeNickname': 'Nickname',
      'timeAgoJustNow': 'Just now',
      'timeAgoMinutes': '%dmin',
      'timeAgoHours': '%dh',
      'timeAgoDays': '%dd',
      'timeAgoWeeks': '%dw',
      'timeAgoMonths': '%dm',
      'timeAgoYears': '%dy',
      'searchCommunityHint': 'Search title, content, comments, nickname',
      'searchEnterQuery': 'Enter a search term',
      'searchNoResults': 'No results for "%s"',
      'postSoon': 'Posts will appear here soon',
      'shortsSoon': 'Short videos will appear here soon',
      'loginSuccess': 'Logged in successfully',
      'loginWithGoogle': 'Continue with Google',
      'loginDividerOr': 'OR',
      'loginPreparing': 'Login is being prepared',
      'signupPreparing': 'Sign up page is being prepared',
      'notReadyYet': 'Not ready yet.',
      'enterEmail': 'Please enter your email',
      'validEmail': 'Please enter a valid email',
      'enterPassword': 'Please enter your password',
      'passwordMin': 'Password must be at least 8 characters',
      'passwordSpecial': 'Password must contain at least one special character',
      'passwordHint': '8+ characters, at least 1 special character',
      'passwordMismatch': 'Passwords do not match',
      'loginErrorWrongPassword': 'Wrong password.',
      'loginErrorEmailNotRegistered': 'No account found with this email.',
      'loginErrorGeneric': 'Login failed. Please try again.',
      'enterNickname': 'Please enter a nickname',
      'nicknameMin': 'Nickname must be at least 2 characters',
      'soon': 'Soon',
      'share': 'Share',
      'copyLink': 'Copy link',
      'shareToApps': 'Share to apps',
      'shareSettings': 'Share settings',
      'linkCopied': 'Link copied',
      'reviewShareImageFailed': 'Could not create the share image.',
      'changeProfilePhoto': 'Change profile photo',
      'pickFromGallery': 'Choose from gallery',
      'removePhoto': 'Remove photo',
      'profilePhotoUpdated': 'Profile photo updated',
      'profilePhotoPreview': 'Preview',
      'edit': 'Edit',
      'edited': 'Edited',
      'delete': 'Delete',
      'report': 'Report',
      'block': 'Block',
      'reportPostTitle': 'Report',
      'reportPostMessage': 'Report this post?',
      'reportSubmitted': 'Report submitted.',
      'blockPostTitle': 'Block post',
      'blockPostMessage': 'Hide this post from your feed?',
      'blockPostDone': 'Post hidden.',
      'save': 'Save',
      'done': 'Done',
      'rotate': 'Rotate',
      'drama': 'Drama',
      'review': 'Review',
      'notifications': 'Alerts',
      'notificationsEmpty': 'Comments, replies and likes on your posts will appear here.',
      'dramaSearchHint': 'Search dramas...',
      'popularSearch': 'People are searching',
      'searchResults': 'Search results',
      'rankingEmpty': 'No data for this period yet. Search or tap items to build the ranking.',
      'periodDay': 'Today',
      'periodWeek': 'Week',
      'periodMonth': 'Month',
      'periodYear': 'Year',
      'recommended': 'Recommended',
      'newReleases': 'New',
      'popularRanking': 'Popular',
      'dramaListTabAll': 'ALL',
      'category': 'Category',
      'genre': 'Genre',
      'target': 'Target',
      'membershipExclusive': 'Membership',
      'dramaExclusive': 'DramaHub Exclusive',
      'rating': 'Rating',
      'participants': 'ratings',
      'ratingsAndComments': 'Ratings & Reviews',
      'writeReview': 'Write a review',
      'writeReviewAction': 'Write a review >',
      'synopsis': 'Synopsis',
      'episodes': 'Episodes',
      'totalEpisodes': 'Total %d eps',
      'episodeLabel': 'Ep %d',
      'dramaViewCount': '%s views',
      'episodeReviewRaterCount': '(%d ratings)',
      'episodeReviewAlreadyExists': 'You already left a review for this episode.',
      'episodeReviewSaveFailed': 'Could not save your review. Please try again.',
      'cast': 'Cast',
      'noCastInfo': 'No cast info available.',
      'firstReview': 'Be the first to write a review!',
      'dramaSpotlightNoReviews': '—',
      'reviewComposerLikedHint': 'Liked this drama',
      'reviewComposerRepliesHint': 'Allow replies on this review',
      'leaveReview': 'Leave a Review',
      'dramaAllReviewsCta': 'ALL REVIEWS >',
      'play': 'Play',
      'similarDramas': 'Similar',
      'ratingHint': 'Rate and write a review',
      'ratingInstruction': 'Rate this drama',
      'reviewPlaceholder': 'Write your review',
      'reviewTagInputHint': 'Add tags',
      'reviewPlaceholderLong': 'Please leave various opinions on plot, subtitles, dubbing, etc!',
      'submitReview': 'Submit',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'ok': 'OK',
      'loginRequired': 'Please log in to write a review',
      'reviewSubmitted': 'Review submitted!',
      'reviewUpdated': 'Review updated!',
      'deleteReviewConfirm': 'Delete this review?',
      'ratingRequired': 'Please select a rating',
      'reviewMinLength': 'Please write at least 5 characters',
      'joinConversation': 'Add a comment…',
      'reply': 'Reply',
      'dislike': 'Dislike',
      'comments': 'Comments',
      'sortByTime': 'Latest',
      'sortByTop': 'Top',
      'commentBeFirst': 'Be the first to comment!',
      'commentWrite': 'Post comment',
      'writeComment': 'Write a comment',
      'activityPoint': ' Activity +1)',
      'replySubmit': 'Post',
      'filter': 'Filter',
      'sort': 'Sort',
      'expand': 'Expand',
      'collapse': 'Collapse',
      'sortByLikes': 'liked',
      'sortByLatest': 'Latest',
      'contentType': 'Content type',
      'all': 'All',
      'interactiveDrama': 'Interactive drama',
      'shortDrama': 'Short drama',
      'reset': 'Reset',
      'apply': 'Apply',
      'tags': 'Tags',
      'ageGap': 'Age gap',
      'reunion': 'Reunion',
      'loveTriangle': 'Love triangle',
      'revenge': 'Revenge',
      'female': 'Female',
      'male': 'Male',
      'lgbtq': 'LGBTQ',
      'region': 'Region',
      'regional': 'Regional',
      'usa': 'USA',
      'asia': 'Asia',
      'dubbing': 'Dubbing',
      'originalAudio': 'Original',
      'dubbed': 'Dubbed',
      'tooLate': 'Too late',
      'lostChild': 'Lost child',
      'affair': 'Affair',
      'friendsToLovers': 'Friends to lovers',
      'harem': 'Harem',
      'salvation': 'Salvation',
      'pregnancy': 'Pregnancy',
      'enemyToLover': 'Enemy to lover',
      'destinedLover': 'Destined lover',
      'watchAd': 'Watch ad',
      'watchAdPlusOne': 'Watch ad +1',
      'freeViewCredits': 'Free views',
      'watchAdToEarn': 'Watch ad to earn free views',
      'noCredits': 'No free views. Watch an ad to earn.',
      'level': 'Level',
      'memberLevel': 'Member level',
      'points': 'pts',
      'levelInfo': 'Level Info',
      'levelInfoSubtitle': 'Earn points through activity to level up.',
      'currentLevel': 'Current Level',
      'totalPointsLabel': 'Total Points',
      'nextLevelNeeded': 'N needed for next level',
      'entireLevelSystem': 'Entire Level System',
      'levelSystemDescription': 'Total points required to reach each level.',
      'attainmentPoint': 'Attainment Point',
      'achievementStatus': 'Status',
      'tableIcon': 'Icon',
      'currentLevelLabel': 'Current',
      'levelAchieved': 'Achieved',
      'levelNotAchieved': '—',
      'writePost': 'Write post',
      'postTitle': 'Title',
      'postTitleHint': 'Give your post a title',
      'postContent': 'Content',
      'postContentHint': 'What do you want to share?',
      'postSubmit': 'Post',
      'postSubmitted': 'Posted!',
      'postSaveFailed': 'Save failed. Please try again.',
      'postSyncFailed': 'Couldn\'t sync to server. Check network and refresh.',
      'postEditSuccess': 'Updated.',
      'postEditFailed': 'Update failed. Please try again.',
      'editPost': 'Edit post',
      'deletePostConfirm': 'Delete this post?',
      'addPhoto': 'Add photo',
      'titleRequired': 'Please enter a title',
      'contentRequired': 'Please enter some content',
      'takePhoto': 'Take photo',
      'pickFromFiles': 'Browse files',
      'maxPhotos': 'Up to 4 photos',
      'titleMinLength': 'Title must be at least 2 characters',
      'contentMinLength': 'Content must be at least 10 characters',
      'postCooldown': 'You can post again in 3 minutes',
      'postLink': 'URL',
      'postLinkHint': 'https://...',
      'messages': 'Messages',
      'profilePublicUserUnavailable': 'Could not load this profile.',
      'profileStatFollow': 'Follow',
      'followScreenTitle': 'Follow',
      'tabFollowing': 'Following',
      'tabFollowers': 'Followers',
      'followEmptyFollowing': 'You are not following anyone yet.',
      'followEmptyFollowers': 'No followers yet.',
      'followButtonFollow': 'Follow',
      'followButtonFollowing': 'Following',
      'followUnfollow': 'Unfollow',
      'loginRequiredForFollow': 'Sign in to use follow.',
      'networkPageTitle': "{name}'s Network",
      'userFollowTitleWithName': "{name}'s Follow",
      'followViewProfile': 'View profile',
      'newMessage': 'New message',
      'noConversations': 'No conversations yet',
      'noConversationsHint': 'Send a message to another member to start.',
      'typeMessage': 'Type a message...',
      'send': 'Send',
      'recipientNickname': 'Recipient nickname',
      'recipientNicknameHint': 'Enter nickname',
      'freeViewCountLabel': 'Free view count',
      'sendMessageToUser': 'Send message',
      'viewUserPosts': 'View posts',
      'viewUserComments': 'View comments',
      'userPostsListTitleSelf': 'Posts',
      'userPostsListTitleOther': 'Posts',
      'userPostsListTitleOtherNamed': "{name}'s Posts",
      'userPublicReviewsTitleNamed': "{name}'s Reviews",
      'userPostsTabPosts': 'Posts',
      'userPostsEmptyPosts': 'No posts by {name} yet.',
      'userPostsEmptyComments': 'No comments by {name} yet.',
      'userCommentsListTitle': 'Comments',
      'activityScore': 'Points',
      'communityRanking': 'Community ranking',
      'seeMore': 'more',
      'watchedDramas': 'Watched dramas',
      'noWatchedDramas': 'You haven\'t watched any dramas.',
      'profileFavoritesTitle': 'FAVORITES',
      'profileFavoritesRemove': 'Remove from favorites',
      'profileFavoritesRemoveConfirm': 'Remove this drama from favorites?',
      'favoriteActivityTitle': "{name}'s Favorites",
      'favoriteActivityHeaderTitle': 'Favorites',
      'favoriteActivityDiaryEmpty':
          'No diary entries for this drama in your watch history yet.',
      'favoriteActivityReviewEmpty': "Haven't reviewed this one yet.",
      'profileRatingsTitle': 'RATINGS',
      'profileRatingsTitleOther': 'RATINGS',
      'profileRatingsCount': '{n} ratings',
      'profileRatingsAverage': 'Average',
    },
    'kr': {
      'searchHint': '무엇이든 찾아보세요',
      'login': '로그인',
      'profile': '프로필',
      'logout': '로그아웃',
      'logoutSuccess': '로그아웃되었습니다',
      'settings': '설정',
      'language': '언어',
      'theme': '테마',
      'themeLight': '라이트',
      'themeDark': '다크',
      'themeSystem': '시스템',
      'notificationSettings': '알림 설정',
      'privacyPolicy': '개인정보 처리방침',
      'helpCenter': '고객센터',
      'myPosts': '게시글',
      'myPostBadge': '내 글',
      'myReviews': '내가 쓴 리뷰',
      'myReviewsEmptyTitle': '아직 작성한 리뷰가 없어요',
      'myReviewsEmptyHint': '드라마 상세에서 리뷰 탭으로 들어가 리뷰를 남겨 보세요.',
      'myReviewsSortTitle': '정렬',
      'myReviewsSortNewest': '최신순',
      'myReviewsSortOldest': '오래된순',
      'saved': '저장',
      'likes': '좋아요',
      'tabLikedPosts': '게시글',
      'tabLikedReviews': '리뷰',
      'likesEmptyPosts': '좋아요한 게시글이 없어요.',
      'likesEmptyReviews': '좋아요한 리뷰가 없어요.',
      'likesEmptyComments': '좋아요한 댓글이 없어요.',
      'likesLoginRequired': '로그인하면 좋아요한 글·리뷰·댓글을 모아볼 수 있어요.',
      'recentActivity': '최근 활동',
      'moreActivity': '활동 더보기',
      'profileRecentActivityEmpty': '별점을 준 드라마가 없어요. 평가하면 여기에 표시돼요.',
      'diary': '다이어리',
      'diaryTitleWithName': '{name}님의 다이어리',
      'diaryTitleWhenAnonymous': '내 다이어리',
      'diaryEmpty': '아직 기록이 없어요. 숏폼에서 드라마를 보면 날짜별로 쌓여요.',
      'tabLists': '리스트',
      'listsTitleWithName': '{name}님의 리스트',
      'listsFilmCount': '{n}',
      'listsCustomHint': '직접 만드는 모음 리스트는 이후 업데이트에서 추가될 예정이에요.',
      'listsWatchlistDescription':
          '드라마 상세에서 보고 싶어요로 담은 작품이에요. 탭하면 포스터 그리드로 이동해요.',
      'listsFilterSoon': '리스트 필터는 이후 업데이트에서 제공될 예정이에요.',
      'listCreateButton': '리스트 만들기',
      'listCreateSuccess': '리스트가 생성되었습니다.',
      'listCreateTitle': '리스트 만들기',
      'listCreateFieldTitle': '제목',
      'listCreateFieldTitleHint': '예) 심장 쫄깃한 복수물',
      'listCreateFieldDescription': '설명',
      'listCreateFieldDescriptionHint': '이 리스트에 어떤 드라마를 모았는지 설명해주세요.',
      'listCreateDramaCount': '드라마 ({count}/{max})',
      'listCreateAddDrama': '드라마 추가',
      'listCreateNoDramaYet': '아직 추가한 드라마가 없습니다.',
      'listCreateSubmit': '리스트 생성하기',
      'listCreateSubmitting': '생성 중...',
      'listCreateErrorNeedTitle': '제목을 한 글자 이상 입력해주세요.',
      'listCreateErrorNeedDrama': '드라마를 1개 이상 추가해주세요.',
      'listCreateDuplicateDialogTitle': '이미 추가됨',
      'listCreateErrorDuplicateDrama': '이미 추가한 드라마입니다.',
      'listCreateErrorMaxDrama': '드라마는 최대 20개까지 추가할 수 있습니다.',
      'listCreateLoginRequired': '로그인 후 리스트를 만들 수 있어요.',
      'listCreateErrorSaveFailed': '리스트를 저장하지 못했어요. 다시 시도해주세요.',
      'listDetailScreenTitle': '리스트',
      'listEditTitle': '리스트 수정',
      'listEditSave': '저장',
      'listDeleteConfirmTitle': '이 리스트를 삭제할까요?',
      'listDeleteConfirmMessage': '되돌릴 수 없어요. 프로필에서 이 리스트가 사라집니다.',
      'listDetailDeleteFailed': '리스트를 삭제하지 못했어요. 다시 시도해주세요.',
      'listDetailEmptyGrid': '아직 담긴 드라마가 없습니다.',
      'listDetailLikePrompt': '좋아요?',
      'listDetailLikesSingular': '좋아요 {n}',
      'listDetailLikesPlural': '좋아요 {n}',
      'listCreateCoverTitle': '리스트 표지 (선택)',
      'listCreateCoverHint':
          '이 리스트 상단에만 보여요. 포스터나 갤러리(+)를 누르면 2:3 크롭 화면이 열려요. 없음으로 해제할 수 있어요.',
      'listCreateCoverNone': '없음',
      'listCreateCoverGalleryPickFailed': '갤러리를 열거나 사진을 불러오지 못했어요.',
      'listCreateCoverUploadFailed': '표지 사진을 올리지 못했어요. 다시 시도해주세요.',
      'listCreateCoverCropTitle': '표지 영역 조정',
      'listCreateCoverImageLoadFailed': '이미지를 불러와 크롭할 수 없어요.',
      'listMultiPickApply': '추가 ({n})',
      'listMultiPickStepLimit': '이 화면에서는 최대 {n}편까지 선택할 수 있어요.',
      'tabWatchlist': '워치리스트',
      'watchlistTitleWithName': '{name}님의 보고 싶어요',
      'likesTitleWithName': '{name}님의 좋아요',
      'tabSavedPosts': '저장한 글',
      'watchlistEmptyTitle': '보고 싶은 드라마를 추가해보세요',
      'watchlistEmptyPublic': '보고 싶은 드라마가 없어요',
      'watchlistRemoveTitle': '보관함에서 뺄까요?',
      'watchlistRemoveMessage': '이 드라마를 Watchlist에서 제거합니다.',
      'dramaWatchlistAdd': '워치리스트',
      'dramaWatchlistRemove': '담아둠',
      'watchlistToastAdded': '보관함에 넣었어요.',
      'watchlistToastRemoved': '보관함에서 뺐어요.',
      'watchlistLoginRequired': '로그인 후 Watchlist를 쓸 수 있어요.',
      'dramaWatchHistoryTooltipAdd': '봤어요',
      'dramaWatchHistoryTooltipRemove': '시청 기록에서 빼기',
      'watchHistoryToastAdded': '시청 기록에 추가됐어요',
      'watchHistoryToastRemoved': '시청 기록에서 제거됐어요',
      'dramaSubpageConfirmWatchTitle': '시청 기록에 추가할까요?',
      'dramaSubpageConfirmWatchBody':
          '다이어리의 시청 기록에 이 드라마가 표시돼요.',
      'dramaSubpageConfirmWatchAlready': '이미 시청 기록에 있어요.',
      'dramaSubpageConfirmWatchlistTitle': '보관함에 넣을까요?',
      'dramaSubpageConfirmWatchlistBody':
          '프로필의 Watchlist에 이 드라마가 표시돼요.',
      'dramaSubpageConfirmWatchlistAlready': '이미 Watchlist에 있어요.',
      'dramaWatchlistSubpageBodyOn': '지금 Watchlist에 담겨 있어요.',
      'dramaWatchlistSubpageBodyOff': '위의 + 를 누르면 Watchlist에 넣을 수 있어요.',
      'dramaWatchActivitySheetTitle': '시청 기록',
      'dramaWatchActivityWatchLabel': '봤어요',
      'dramaWatchActivityOptionalStars': '별점 (선택)',
      'dramaWatchActivityReviewHint': '리뷰 (선택, 별점을 먼저 골라 주세요)',
      'dramaWatchActivityPosted': '피드에 올렸어요.',
      'dramaWatchActivityLoginRequired': '로그인 후 작성할 수 있어요.',
      'dramaWatchActivityWatchOrdinal1': '첫 시청',
      'dramaWatchActivityWatchOrdinal2': '두 번째 시청',
      'dramaWatchActivityWatchOrdinal3': '세 번째 시청',
      'dramaWatchActivityWatchOrdinalN': '{n}번째 시청',
      'dramaWatchActivityHeaderRating': '별점',
      'dramaWatchActivityHeaderReview': '리뷰',
      'dramaBottomActionWatch': '봤어요',
      'dramaBottomActionRate': '평가',
      'dramaBottomActionReview': '리뷰',
      'dramaBottomActionWatchlist': '워치리스트',
      'statsBarWatchersLabel': '시청',
      'statsBarReviewsLabel': '리뷰',
      'statsBarListsLabel': '리스트',
      'statsBarFirstWatcher': '첫 시청자?',
      'statsBarWriteReview': '리뷰 쓰기',
      'statsBarMakeList': '리스트',
      'statsBarComingSoon': '준비 중이에요',
      'dramaReviewsTabPopular': '인기',
      'dramaReviewsTabAll': '전체',
      'dramaListsEmptyFeed': '드라마 목록을 불러오면 리스트 미리보기가 표시돼요.',
      'tagDramaListEmpty': '이 태그에 맞는 작품이 카탈로그에 없어요.',
      'savedPostsEmptyTitle': '저장한 글이 없습니다',
      'savedPostsEmptyHint': '게시판에서 글의 저장 버튼을 눌러 추가해 보세요',
      'home': '홈',
      'shorts': '숏폼',
      'popular': '인기글',
      'freeBoard': '자유게시판',
      'questionBoard': '질문게시판',
      'welcomeLogin': 'DramaHub에 오신 것을\n환영합니다',
      'loginSubtitle': '이메일과 비밀번호를 입력해주세요',
      'email': '이메일',
      'password': '비밀번호',
      'signUp': '회원가입',
      'noAccount': '계정이 없으신가요? ',
      'hasAccount': '이미 계정이 있으신가요? ',
      'welcomeSignup': 'DramaHub와 함께\n소통해보세요',
      'signupSubtitle': '선택한 언어로 앱이 표시됩니다. 같은 언어를 선택한 사용자에게만 글이 보입니다.',
      'country': '국가',
      'nickname': '닉네임',
      'nicknameHint': '다른 사용자에게 보여질 이름',
      'passwordConfirm': '비밀번호 확인',
      'signUpButton': '가입하기',
      'popularPlaceholder': '인기글',
      'freeBoardPlaceholder': '자유게시판',
      'tabHot': '트렌드',
      'tabGeneral': '자유',
      'tabQnA': '질문',
      'talkAskFeedLayoutSwitchToCards': '카드형',
      'talkAskFeedLayoutSwitchToList': '목록형',
      'tabReviews': '리뷰',
      'trendTabHint': '좋아요 10개 이상 또는 조회수 100 이상인 글이 표시돼요.',
      'reviewsTabEmpty': '드라마를 검색해 첫 리뷰를 남겨 보세요.',
      'spoilerBadge': '스포일러 포함',
      'reviewSpoilerDisclaimer': '리뷰에 스포일러가 포함될 수 있습니다.',
      'reviewSpoilerTapToRevealLetterboxd': '스포일러가 포함될 수 있어요. 탭하면 본문이 공개됩니다.',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'letterboxdReviewDetailTabReview': '리뷰',
      'letterboxdReviewDetailTabPostWithCount': '댓글 {n}',
      'letterboxdReviewDetailAppBarTitle': '{name}님의 리뷰',
      'letterboxdReviewWatchedLine': '시청 {date}',
      'selectDrama': '드라마 검색',
      'reviewDramaSearchHint': '숏드라마 검색',
      'ratingLabel': '별점',
      'spoilerToggle': '스포일러가 포함되어 있어요',
      'reviewNeedDramaRating': '리뷰를 등록하려면 드라마와 별점을 선택해 주세요.',
      'reviewNeedDrama': '리뷰를 등록하려면 드라마를 선택해 주세요.',
      'reviewPleaseSelectRating': '별점을 선택해 주세요.',
      'search': '검색',
      'searchScopeTitleAndBody': '제목+내용',
      'searchScopeTitle': '제목',
      'searchScopeBody': '내용',
      'searchScopeComment': '댓글',
      'searchScopeNickname': '닉네임',
      'timeAgoJustNow': '방금 전',
      'timeAgoMinutes': '%d분 전',
      'timeAgoHours': '%d시간 전',
      'timeAgoDays': '%d일 전',
      'timeAgoWeeks': '%d주 전',
      'timeAgoMonths': '%d개월 전',
      'timeAgoYears': '%d년 전',
      'searchCommunityHint': '제목, 내용, 댓글, 닉네임 검색',
      'searchEnterQuery': '검색어를 입력해 주세요',
      'searchNoResults': '"%s" 검색 결과가 없어요',
      'postSoon': '곧 게시글이 여기에 표시됩니다',
      'shortsSoon': '곧 숏폼 영상이 여기에 표시됩니다',
      'loginSuccess': '로그인했습니다',
      'loginWithGoogle': 'Google로 로그인',
      'loginDividerOr': '또는',
      'loginPreparing': '로그인 준비 중입니다',
      'signupPreparing': '회원가입 페이지 준비 중입니다',
      'notReadyYet': '아직 준비 중입니다',
      'enterEmail': '이메일을 입력해주세요',
      'validEmail': '올바른 이메일 형식을 입력해주세요',
      'enterPassword': '비밀번호를 입력해주세요',
      'passwordMin': '비밀번호는 8자 이상이어야 합니다',
      'passwordSpecial': '비밀번호에 특수문자를 1개 이상 포함해주세요',
      'passwordHint': '8자 이상, 특수문자 1개 이상',
      'passwordMismatch': '비밀번호가 일치하지 않습니다',
      'loginErrorWrongPassword': '비밀번호가 틀렸어요.',
      'loginErrorEmailNotRegistered': '가입된 이메일이 없어요.',
      'loginErrorGeneric': '로그인에 실패했어요. 다시 시도해 주세요.',
      'enterNickname': '닉네임을 입력해주세요',
      'nicknameMin': '닉네임은 2자 이상이어야 합니다',
      'soon': '곧',
      'share': '공유',
      'copyLink': '링크 복사',
      'shareToApps': '앱으로 공유',
      'shareSettings': '공유 설정',
      'linkCopied': '링크가 복사되었습니다',
      'reviewShareImageFailed': '공유 이미지를 만들지 못했어요.',
      'changeProfilePhoto': '프로필 사진 변경',
      'pickFromGallery': '갤러리에서 선택',
      'removePhoto': '사진 삭제',
      'profilePhotoUpdated': '프로필 사진이 변경되었어요',
      'profilePhotoPreview': '미리 보기',
      'edit': '수정',
      'edited': '수정됨',
      'delete': '삭제',
      'report': '신고하기',
      'block': '차단',
      'reportPostTitle': '신고하기',
      'reportPostMessage': '이 게시글을 신고하시겠습니까?',
      'reportSubmitted': '신고가 접수되었습니다.',
      'blockPostTitle': '글 차단',
      'blockPostMessage': '이 글을 피드에서 숨기시겠습니까?',
      'blockPostDone': '해당 글을 차단했습니다.',
      'save': '저장',
      'done': '완료',
      'rotate': '회전',
      'drama': '드라마',
      'review': '리뷰',
      'notifications': '알림',
      'notificationsEmpty': '내가 쓴 글에 댓글·대댓글·좋아요가 오면 여기에 표시됩니다.',
      'dramaSearchHint': '드라마 검색...',
      'popularSearch': '인기 검색',
      'searchResults': '검색 결과',
      'rankingEmpty': '이 기간에 아직 데이터가 없어요. 검색하거나 항목을 눌러보면 순위가 쌓여요.',
      'periodDay': '오늘',
      'periodWeek': '이번 주',
      'periodMonth': '이번 달',
      'periodYear': '올해',
      'recommended': '추천',
      'newReleases': '신작',
      'popularRanking': '인기 순위',
      'dramaListTabAll': '전체',
      'category': '카테고리',
      'genre': '장르',
      'target': '대상',
      'membershipExclusive': '멤버십 전용',
      'dramaExclusive': 'DramaHub 전용',
      'rating': '평점',
      'participants': '참여',
      'ratingsAndComments': '평점 & 리뷰',
      'writeReview': '리뷰 작성하기',
      'writeReviewAction': '리뷰 작성하기 >',
      'synopsis': '줄거리',
      'episodes': '회차',
      'totalEpisodes': '총 %d편',
      'episodeLabel': '%d화',
      'dramaViewCount': '%s 조회수',
      'episodeReviewRaterCount': '(%d명 참여)',
      'episodeReviewAlreadyExists': '이미 이 회차에 리뷰를 작성했습니다.',
      'episodeReviewSaveFailed': '리뷰를 저장하지 못했습니다. 다시 시도해 주세요.',
      'cast': '배우',
      'noCastInfo': '출연 정보가 없습니다.',
      'firstReview': '가장 먼저 리뷰를 작성해 보세요!',
      'dramaSpotlightNoReviews': '—',
      'reviewComposerLikedHint': '이 작품이 좋았어요',
      'reviewComposerRepliesHint': '댓글 허용',
      'leaveReview': '리뷰 남기기',
      'dramaAllReviewsCta': '전체 리뷰 >',
      'play': '재생',
      'similarDramas': '비슷한 작품',
      'ratingHint': '"이 작품, 당신은 몇 점?"',
      'ratingInstruction': '평점을 매겨 주세요',
      'reviewPlaceholder': '리뷰 작성하기',
      'reviewTagInputHint': '태그 추가',
      'reviewPlaceholderLong': '줄거리·자막·더빙 등에 대한 다양한 의견을 남겨주세요!',
      'submitReview': '등록하기',
      'submit': '등록',
      'cancel': '취소',
      'ok': '확인',
      'loginRequired': '리뷰를 쓰려면 로그인해주세요',
      'reviewSubmitted': '리뷰가 등록되었습니다!',
      'reviewUpdated': '리뷰가 수정되었습니다!',
      'deleteReviewConfirm': '이 리뷰를 삭제할까요?',
      'ratingRequired': '평점을 매겨 주세요',
      'reviewMinLength': '리뷰는 5자 이상 입력해 주세요',
      'joinConversation': '댓글을 입력하세요…',
      'reply': '답글',
      'dislike': '싫어요',
      'comments': '댓글',
      'sortByTime': '최신순',
      'sortByTop': '추천순',
      'commentBeFirst': '가장 먼저 댓글을 남겨보세요!',
      'commentWrite': '댓글 남기기',
      'writeComment': '댓글 쓰기',
      'activityPoint': ' 활동지수 +1)',
      'replySubmit': '답글 달기',
      'filter': '필터',
      'sort': '정렬',
      'expand': '펼치기',
      'collapse': '접기',
      'sortByLikes': '좋아요 순',
      'sortByLatest': '최신순',
      'contentType': '콘텐츠 유형',
      'all': '모두',
      'interactiveDrama': '인터랙티브 드라마',
      'shortDrama': '숏폼 드라마',
      'reset': '초기화',
      'apply': '적용',
      'tags': '태그',
      'ageGap': '나이차',
      'reunion': '재회',
      'loveTriangle': '삼각관계',
      'revenge': '복수',
      'female': '여성',
      'male': '남성',
      'lgbtq': 'LGBTQ',
      'region': '지역',
      'regional': '지역',
      'usa': '미국',
      'asia': '아시아',
      'dubbing': '더빙',
      'originalAudio': '원음',
      'dubbed': '더빙',
      'tooLate': '이미 늦음',
      'lostChild': '길 잃은 어린이',
      'affair': '불륜',
      'friendsToLovers': '친구에서 연인으로',
      'harem': '하렘',
      'salvation': '구원',
      'pregnancy': '임신',
      'enemyToLover': '적에서 연인으로',
      'destinedLover': '운명적인 연인',
      'watchAd': '광고 시청',
      'watchAdPlusOne': '광고 보고 +1회',
      'freeViewCredits': '무료 시청',
      'watchAdToEarn': '광고 시청으로 무료 시청 횟수 획득',
      'noCredits': '무료 시청 횟수가 없어요. 광고를 시청해보세요.',
      'level': '레벨',
      'memberLevel': '회원레벨',
      'points': '점',
      'levelInfo': '레벨 정보',
      'levelInfoSubtitle': '활동으로 포인트를 쌓아 레벨을 올려보세요.',
      'currentLevel': '현재 레벨',
      'totalPointsLabel': '총 Point',
      'nextLevelNeeded': '다음 레벨까지 N 필요',
      'entireLevelSystem': '전체 레벨 시스템',
      'levelSystemDescription': '각 레벨에 도달하기 위해 필요한 총 포인트입니다.',
      'attainmentPoint': '도달 Point',
      'achievementStatus': '달성 여부',
      'tableIcon': '아이콘',
      'currentLevelLabel': '현재',
      'levelAchieved': '달성',
      'levelNotAchieved': '—',
      'writePost': '글쓰기',
      'postTitle': '제목',
      'postTitleHint': '제목을 입력하세요',
      'postContent': '내용',
      'postContentHint': '자유롭게 작성해보세요',
      'postSubmit': '등록',
      'postSubmitted': '등록되었어요!',
      'postSaveFailed': '저장에 실패했어요. 다시 시도해주세요.',
      'postSyncFailed': '서버 동기화에 실패했어요. 네트워크 확인 후 새로고침해주세요.',
      'postEditSuccess': '수정되었어요.',
      'postEditFailed': '수정에 실패했어요. 다시 시도해주세요.',
      'editPost': '글 수정',
      'deletePostConfirm': '이 글을 삭제할까요?',
      'addPhoto': '사진 추가',
      'titleRequired': '제목을 입력해주세요',
      'contentRequired': '내용을 입력해주세요',
      'takePhoto': '카메라로 촬영',
      'pickFromFiles': '파일에서 선택',
      'maxPhotos': '최대 4장까지',
      'titleMinLength': '제목은 2자 이상 입력해주세요',
      'contentMinLength': '내용은 10자 이상 입력해주세요',
      'postCooldown': '3분 후에 다시 글을 쓸 수 있어요',
      'postLink': '링크',
      'postLinkHint': 'https://...',
      'messages': '쪽지',
      'profilePublicUserUnavailable': '프로필을 불러올 수 없어요.',
      'profileStatFollow': '팔로우',
      'followScreenTitle': '팔로우',
      'tabFollowing': '팔로잉',
      'tabFollowers': '팔로워',
      'followEmptyFollowing': '팔로우한 계정이 없어요.',
      'followEmptyFollowers': '아직 팔로워가 없어요.',
      'followButtonFollow': '팔로우',
      'followButtonFollowing': '팔로잉',
      'followUnfollow': '팔로우 취소',
      'loginRequiredForFollow': '팔로우를 사용하려면 로그인해 주세요.',
      'networkPageTitle': '{name}님의 네트워크',
      'userFollowTitleWithName': '{name}님의 팔로우',
      'followViewProfile': '프로필 보기',
      'newMessage': '새 쪽지',
      'noConversations': '대화가 없습니다',
      'noConversationsHint': '회원에게 쪽지를 보내 대화를 시작해보세요.',
      'typeMessage': '쪽지 내용 입력...',
      'send': '보내기',
      'recipientNickname': '받는 사람 닉네임',
      'recipientNicknameHint': '닉네임 입력',
      'freeViewCountLabel': '무료 시청 횟수',
      'sendMessageToUser': '쪽지 보내기',
      'viewUserPosts': '작성글 보기',
      'viewUserComments': '작성댓글 보기',
      'userPostsListTitleSelf': '게시글',
      'userPostsListTitleOther': '게시글',
      'userPostsListTitleOtherNamed': '{name}님의 게시글',
      'userPublicReviewsTitleNamed': '{name}님의 리뷰',
      'userPostsTabPosts': '게시글',
      'userPostsEmptyPosts': '{name}님이 작성한 글이 없어요.',
      'userPostsEmptyComments': '{name}님이 작성한 댓글이 없어요.',
      'userCommentsListTitle': '댓글',
      'activityScore': '활동지수',
      'communityRanking': '커뮤니티 랭킹',
      'seeMore': '더보기',
      'watchedDramas': '내가 본 드라마',
      'noWatchedDramas': '시청한 드라마가 없어요',
      'profileFavoritesTitle': '최애',
      'profileFavoritesRemove': '최애에서 제거',
      'profileFavoritesRemoveConfirm': '이 드라마를 최애에서 제거할까요?',
      'favoriteActivityTitle': '{name}님의 최애',
      'favoriteActivityHeaderTitle': '최애',
      'favoriteActivityDiaryEmpty': '이 작품에 대한 시청 기록(다이어리)이 아직 없어요.',
      'favoriteActivityReviewEmpty': '이 작품에 대한 리뷰를 아직 쓰지 않았어요.',
      'profileRatingsTitle': '나의 별점',
      'profileRatingsTitleOther': '별점',
      'profileRatingsCount': '평가 {n}개',
      'profileRatingsAverage': '평균',
    },
    'cn': {
      'searchHint': '搜索任何内容',
      'login': '登录',
      'profile': '个人资料',
      'logout': '退出登录',
      'logoutSuccess': '已退出登录',
      'settings': '设置',
      'language': '语言',
      'theme': '主题',
      'themeLight': '浅色',
      'themeDark': '深色',
      'themeSystem': '跟随系统',
      'notificationSettings': '通知设置',
      'privacyPolicy': '隐私政策',
      'helpCenter': '帮助中心',
      'myPosts': '帖子',
      'myPostBadge': '我的',
      'myReviews': '我写的评论',
      'myReviewsEmptyTitle': '还没有剧评',
      'myReviewsEmptyHint': '打开剧集详情，在剧评区写下你的第一条评论。',
      'myReviewsSortTitle': '排序',
      'myReviewsSortNewest': '最新在前',
      'myReviewsSortOldest': '最早在前',
      'saved': '收藏',
      'likes': '喜欢',
      'tabLikedPosts': '帖子',
      'tabLikedReviews': '剧评',
      'likesEmptyPosts': '还没有喜欢的帖子。',
      'likesEmptyReviews': '还没有喜欢的剧评。',
      'likesEmptyComments': '还没有喜欢的评论。',
      'likesLoginRequired': '登录后可查看喜欢的帖子、剧评和评论。',
      'recentActivity': '最近动态',
      'moreActivity': '更多动态',
      'profileRecentActivityEmpty': '还没有打过分的剧。给剧打分后会显示在这里。',
      'diary': '观影日记',
      'diaryTitleWithName': '{name}的观影日记',
      'diaryTitleWhenAnonymous': '我的观影日记',
      'diaryEmpty': '还没有记录。在短视频里观看剧集后会按日期显示。',
      'tabLists': '片单',
      'listsTitleWithName': '{name}的片单',
      'listsFilmCount': '{n}',
      'listsCustomHint': '自定义片单功能将在后续版本开放。',
      'listsWatchlistDescription': '在剧集详情中标记「想看」的短剧会显示在这里。点按进入海报网格。',
      'listsFilterSoon': '片单筛选功能将在后续版本提供。',
      'listCreateButton': '创建片单',
      'listCreateSuccess': '片单已创建。',
      'listCreateTitle': '创建片单',
      'listCreateFieldTitle': '标题',
      'listCreateFieldTitleHint': '例如：高能复仇短剧',
      'listCreateFieldDescription': '说明',
      'listCreateFieldDescriptionHint': '请说明这个片单的主题。',
      'listCreateDramaCount': '剧集（{count}/{max}）',
      'listCreateAddDrama': '添加剧集',
      'listCreateNoDramaYet': '还没有添加剧集。',
      'listCreateSubmit': '创建片单',
      'listCreateSubmitting': '创建中...',
      'listCreateErrorNeedTitle': '请至少输入一个字的标题。',
      'listCreateErrorNeedDrama': '请至少添加一部剧集。',
      'listCreateDuplicateDialogTitle': '已添加',
      'listCreateErrorDuplicateDrama': '该剧已添加。',
      'listCreateErrorMaxDrama': '最多可添加20部剧集。',
      'listCreateLoginRequired': '登录后可创建片单。',
      'listCreateErrorSaveFailed': '保存失败，请重试。',
      'listDetailScreenTitle': '片单',
      'listEditTitle': '编辑片单',
      'listEditSave': '保存',
      'listDeleteConfirmTitle': '删除该片单？',
      'listDeleteConfirmMessage': '此操作无法撤销，片单将从你的资料中移除。',
      'listDetailDeleteFailed': '删除失败，请重试。',
      'listDetailEmptyGrid': '该片单中还没有剧集。',
      'listDetailLikePrompt': '赞？',
      'listDetailLikesSingular': '{n} 次赞',
      'listDetailLikesPlural': '{n} 次赞',
      'listCreateCoverTitle': '片单封面（可选）',
      'listCreateCoverHint':
          '仅显示在片单页顶部。点击海报或相册(+)进入裁剪(2:3)。选「无」可清除。',
      'listCreateCoverNone': '无',
      'listCreateCoverGalleryPickFailed': '无法打开相册或读取图片。',
      'listCreateCoverUploadFailed': '封面上传失败，请重试。',
      'listCreateCoverCropTitle': '调整封面',
      'listCreateCoverImageLoadFailed': '无法加载该图片进行裁剪。',
      'listMultiPickApply': '添加 ({n})',
      'listMultiPickStepLimit': '在此页面最多可选择 {n} 部。',
      'tabWatchlist': '想看',
      'watchlistTitleWithName': '{name}的想看列表',
      'likesTitleWithName': '{name}的喜欢',
      'tabSavedPosts': '收藏的帖子',
      'watchlistEmptyTitle': '想看列表还是空的',
      'watchlistEmptyPublic': '暂无想看作品',
      'watchlistRemoveTitle': '从想看列表移除？',
      'watchlistRemoveMessage': '该剧将从您的想看列表中移除。',
      'dramaWatchlistAdd': '想看',
      'dramaWatchlistRemove': '已加入',
      'watchlistToastAdded': '已加入想看列表。',
      'watchlistToastRemoved': '已从想看列表移除。',
      'watchlistLoginRequired': '登录后可使用想看列表。',
      'dramaWatchHistoryTooltipAdd': '标记为看过',
      'dramaWatchHistoryTooltipRemove': '从观影记录移除',
      'watchHistoryToastAdded': '已加入观影记录。',
      'watchHistoryToastRemoved': '已从观影记录移除。',
      'dramaSubpageConfirmWatchTitle': '加入观影记录？',
      'dramaSubpageConfirmWatchBody': '该剧会出现在你的日记观影记录中。',
      'dramaSubpageConfirmWatchAlready': '该剧已在观影记录里。',
      'dramaSubpageConfirmWatchlistTitle': '加入想看列表？',
      'dramaSubpageConfirmWatchlistBody': '该剧会出现在个人资料的想看列表中。',
      'dramaSubpageConfirmWatchlistAlready': '该剧已在想看列表里。',
      'dramaWatchlistSubpageBodyOn': '该剧已在个人资料的想看列表中。',
      'dramaWatchlistSubpageBodyOff': '点右上角 + 即可加入想看列表。',
      'dramaWatchActivitySheetTitle': '记录观看',
      'dramaWatchActivityWatchLabel': '已看',
      'dramaWatchActivityOptionalStars': '评分（可选）',
      'dramaWatchActivityReviewHint': '剧评（可选，请先选择评分）',
      'dramaWatchActivityPosted': '已发布到动态。',
      'dramaWatchActivityLoginRequired': '登录后即可发布。',
      'dramaWatchActivityWatchOrdinal1': '首次观看',
      'dramaWatchActivityWatchOrdinal2': '第二次观看',
      'dramaWatchActivityWatchOrdinal3': '第三次观看',
      'dramaWatchActivityWatchOrdinalN': '第{n}次观看',
      'dramaWatchActivityHeaderRating': '评分',
      'dramaWatchActivityHeaderReview': '剧评',
      'dramaBottomActionWatch': '看过',
      'dramaBottomActionRate': '评分',
      'dramaBottomActionReview': '剧评',
      'dramaBottomActionWatchlist': '想看',
      'statsBarWatchersLabel': '看过',
      'statsBarReviewsLabel': '剧评',
      'statsBarListsLabel': '片单',
      'statsBarFirstWatcher': '成为首位观众？',
      'statsBarWriteReview': '来写剧评',
      'statsBarMakeList': '创建片单',
      'statsBarComingSoon': '即将上线',
      'dramaReviewsTabPopular': '热门',
      'dramaReviewsTabAll': '全部',
      'dramaListsEmptyFeed': '加载剧集目录后即可预览示例片单。',
      'tagDramaListEmpty': '目录中还没有带此标签的剧集。',
      'savedPostsEmptyTitle': '还没有收藏的帖子',
      'savedPostsEmptyHint': '在社区帖子里点书签即可收藏。',
      'home': '首页',
      'shorts': '短视频',
      'popular': '热门',
      'freeBoard': '自由讨论',
      'questionBoard': '问答板',
      'welcomeLogin': '欢迎来到\nDramaHub',
      'loginSubtitle': '请输入邮箱和密码',
      'email': '邮箱',
      'password': '密码',
      'signUp': '注册',
      'noAccount': '还没有账号？',
      'hasAccount': '已有账号？',
      'welcomeSignup': '与DramaHub一起\n交流吧',
      'signupSubtitle': '应用将以此语言显示。您的帖子仅对选择相同语言的用户可见。',
      'country': '国家',
      'nickname': '昵称',
      'nicknameHint': '其他用户看到的名称',
      'passwordConfirm': '确认密码',
      'signUpButton': '注册',
      'popularPlaceholder': '热门',
      'freeBoardPlaceholder': '自由讨论',
      'tabHot': '热门',
      'tabGeneral': '综合',
      'tabQnA': '问答',
      'talkAskFeedLayoutSwitchToCards': '卡片视图',
      'talkAskFeedLayoutSwitchToList': '列表视图',
      'tabReviews': '剧评',
      'trendTabHint': '点赞≥10或浏览≥100的帖子会显示在这里。',
      'reviewsTabEmpty': '搜索剧集并发布第一条剧评。',
      'spoilerBadge': '含剧透',
      'reviewSpoilerDisclaimer': '本评论可能含有剧透。',
      'reviewSpoilerTapToRevealLetterboxd': '本剧评可能含有剧透。点击显示正文。',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'letterboxdReviewDetailTabReview': '剧评',
      'letterboxdReviewDetailTabPostWithCount': '评论 {n}',
      'letterboxdReviewDetailAppBarTitle': '{name}的剧评',
      'letterboxdReviewWatchedLine': '观看 {date}',
      'selectDrama': '搜索剧集',
      'reviewDramaSearchHint': '搜索短剧',
      'ratingLabel': '评分',
      'spoilerToggle': '含剧透内容',
      'reviewNeedDramaRating': '发布剧评前请选择剧集和星级。',
      'reviewNeedDrama': '发布剧评前请选择剧集。',
      'reviewPleaseSelectRating': '请选择星级。',
      'search': '搜索',
      'searchScopeTitleAndBody': '标题+内容',
      'searchScopeTitle': '标题',
      'searchScopeBody': '内容',
      'searchScopeComment': '评论',
      'searchScopeNickname': '昵称',
      'timeAgoJustNow': '刚刚',
      'timeAgoMinutes': '%d分钟前',
      'timeAgoHours': '%d小时前',
      'timeAgoDays': '%d天前',
      'timeAgoWeeks': '%d周前',
      'timeAgoMonths': '%d个月前',
      'timeAgoYears': '%d年前',
      'searchCommunityHint': '搜索标题、内容、评论、昵称',
      'searchEnterQuery': '请输入搜索词',
      'searchNoResults': '没有找到"%s"的结果',
      'postSoon': '帖子将很快显示在这里',
      'shortsSoon': '短视频将很快显示在这里',
      'loginSuccess': '登录成功',
      'loginWithGoogle': '使用Google登录',
      'loginDividerOr': '或',
      'loginPreparing': '登录功能准备中',
      'signupPreparing': '注册页面准备中',
      'notReadyYet': '功能准备中',
      'enterEmail': '请输入邮箱',
      'validEmail': '请输入有效的邮箱格式',
      'enterPassword': '请输入密码',
      'passwordMin': '密码至少8个字符',
      'passwordSpecial': '密码至少包含1个特殊字符',
      'passwordHint': '8个字符以上，至少1个特殊字符',
      'passwordMismatch': '两次密码不一致',
      'loginErrorWrongPassword': '密码错误。',
      'loginErrorEmailNotRegistered': '没有找到该邮箱的账号。',
      'loginErrorGeneric': '登录失败，请重试。',
      'enterNickname': '请输入昵称',
      'nicknameMin': '昵称至少2个字符',
      'soon': '即将',
      'share': '分享',
      'copyLink': '复制链接',
      'shareToApps': '分享到应用',
      'shareSettings': '分享设置',
      'linkCopied': '链接已复制',
      'reviewShareImageFailed': '无法生成分享图片。',
      'changeProfilePhoto': '更换头像',
      'pickFromGallery': '从相册选择',
      'removePhoto': '删除照片',
      'profilePhotoUpdated': '头像已更新',
      'profilePhotoPreview': '预览',
      'edit': '编辑',
      'edited': '已编辑',
      'delete': '删除',
      'report': '举报',
      'block': '屏蔽',
      'reportPostTitle': '举报',
      'reportPostMessage': '确定举报此帖？',
      'reportSubmitted': '举报已提交。',
      'blockPostTitle': '屏蔽帖子',
      'blockPostMessage': '在动态中隐藏此帖？',
      'blockPostDone': '已屏蔽该帖。',
      'save': '保存',
      'done': '完成',
      'rotate': '旋转',
      'drama': '剧集',
      'review': '评论',
      'notifications': '通知',
      'notificationsEmpty': '您收到的评论、回复和点赞将显示在这里。',
      'dramaSearchHint': '搜索剧集...',
      'popularSearch': '热门搜索',
      'searchResults': '搜索结果',
      'rankingEmpty': '该时段暂无数据。搜索或点击作品后会出现排名。',
      'periodDay': '今天',
      'periodWeek': '本周',
      'periodMonth': '本月',
      'periodYear': '今年',
      'recommended': '推荐',
      'newReleases': '新作',
      'popularRanking': '人气排行',
      'dramaListTabAll': '全部',
      'category': '分类',
      'genre': '类型',
      'target': '受众',
      'membershipExclusive': '会员专享',
      'dramaExclusive': 'DramaHub 独家',
      'rating': '评分',
      'participants': '参与',
      'ratingsAndComments': '评分与评论',
      'writeReview': '写评论',
      'writeReviewAction': '写评论 >',
      'synopsis': '剧情简介',
      'episodes': '集数',
      'totalEpisodes': '共%d集',
      'episodeLabel': '第%d集',
      'dramaViewCount': '%s 次观看',
      'episodeReviewRaterCount': '（%d 人评分）',
      'episodeReviewAlreadyExists': '您已为本集留下评论。',
      'episodeReviewSaveFailed': '评论保存失败，请重试。',
      'cast': '演员',
      'noCastInfo': '暂无演员信息。',
      'firstReview': '来写第一条评论吧！',
      'dramaSpotlightNoReviews': '—',
      'reviewComposerLikedHint': '喜欢这部剧',
      'reviewComposerRepliesHint': '允许评论',
      'leaveReview': '留下评论',
      'dramaAllReviewsCta': '全部评论 >',
      'play': '播放',
      'similarDramas': '类似作品',
      'ratingHint': '评分并写评论',
      'ratingInstruction': '请为这部剧评分',
      'reviewPlaceholder': '撰写剧评',
      'reviewTagInputHint': '添加标签',
      'reviewPlaceholderLong': '请分享对剧情、字幕、配音等的各种看法！',
      'submitReview': '提交',
      'submit': '提交',
      'cancel': '取消',
      'ok': '确定',
      'loginRequired': '请登录后再写评论',
      'reviewSubmitted': '评论已提交！',
      'reviewUpdated': '评论已修改！',
      'deleteReviewConfirm': '确定删除此评论？',
      'ratingRequired': '请选择评分',
      'reviewMinLength': '请输入至少5个字的评论',
      'joinConversation': '添加评论…',
      'reply': '回复',
      'dislike': '踩',
      'comments': '评论',
      'sortByTime': '最新',
      'sortByTop': '推荐',
      'commentBeFirst': '来写第一条评论吧！',
      'commentWrite': '写评论',
      'writeComment': '写评论',
      'activityPoint': ' 活跃度 +1)',
      'replySubmit': '发布',
      'filter': '筛选',
      'sort': '排序',
      'expand': '展开',
      'collapse': '收起',
      'sortByLikes': '按赞数',
      'sortByLatest': '最新',
      'contentType': '内容类型',
      'all': '全部',
      'interactiveDrama': '互动剧',
      'shortDrama': '短剧',
      'reset': '重置',
      'apply': '应用',
      'tags': '标签',
      'ageGap': '年龄差',
      'reunion': '重逢',
      'loveTriangle': '三角恋',
      'revenge': '复仇',
      'female': '女性',
      'male': '男性',
      'lgbtq': 'LGBTQ',
      'region': '地区',
      'regional': '地区',
      'usa': '美国',
      'asia': '亚洲',
      'dubbing': '配音',
      'originalAudio': '原音',
      'dubbed': '配音',
      'tooLate': '为时已晚',
      'lostChild': '迷路的孩子',
      'affair': '婚外情',
      'friendsToLovers': '朋友变恋人',
      'harem': '后宫',
      'salvation': '救赎',
      'pregnancy': '怀孕',
      'enemyToLover': '敌人变恋人',
      'destinedLover': '命中注定的恋人',
      'watchAd': '观看广告',
      'watchAdPlusOne': '观看广告 +1次',
      'freeViewCredits': '免费观看',
      'watchAdToEarn': '观看广告获得免费观看次数',
      'noCredits': '没有免费观看次数。请观看广告。',
      'level': '等级',
      'memberLevel': '会员等级',
      'points': '分',
      'levelInfo': '等级信息',
      'levelInfoSubtitle': '通过活动积累积分提升等级。',
      'currentLevel': '当前等级',
      'totalPointsLabel': '总积分',
      'nextLevelNeeded': '距下一级还需 N',
      'entireLevelSystem': '等级体系',
      'levelSystemDescription': '达到各等级所需累计积分。',
      'attainmentPoint': '达成积分',
      'achievementStatus': '达成状态',
      'tableIcon': '图标',
      'currentLevelLabel': '当前',
      'levelAchieved': '已达成',
      'levelNotAchieved': '—',
      'writePost': '发帖',
      'postTitle': '标题',
      'postTitleHint': '输入标题',
      'postContent': '内容',
      'postContentHint': '写下你想分享的内容',
      'postSubmit': '发布',
      'postSubmitted': '发布成功！',
      'postSaveFailed': '保存失败，请重试。',
      'postSyncFailed': '无法同步到服务器，请检查网络后刷新。',
      'postEditSuccess': '已更新。',
      'postEditFailed': '更新失败，请重试。',
      'editPost': '编辑帖子',
      'deletePostConfirm': '确定删除此帖？',
      'addPhoto': '添加图片',
      'titleRequired': '请输入标题',
      'contentRequired': '请输入内容',
      'takePhoto': '拍照',
      'pickFromFiles': '从文件选择',
      'maxPhotos': '最多4张',
      'titleMinLength': '标题至少2个字符',
      'contentMinLength': '内容至少10个字符',
      'postCooldown': '3分钟后再发帖',
      'postLink': '链接',
      'postLinkHint': 'https://...',
      'messages': '私信',
      'profilePublicUserUnavailable': '无法加载该资料。',
      'profileStatFollow': '关注',
      'followScreenTitle': '关注',
      'tabFollowing': '正在关注',
      'tabFollowers': '粉丝',
      'followEmptyFollowing': '还没有关注任何人。',
      'followEmptyFollowers': '还没有粉丝。',
      'followButtonFollow': '关注',
      'followButtonFollowing': '已关注',
      'followUnfollow': '取消关注',
      'loginRequiredForFollow': '请登录后使用关注功能。',
      'networkPageTitle': '{name} 的社交网络',
      'userFollowTitleWithName': '{name}的关注',
      'followViewProfile': '查看主页',
      'newMessage': '新私信',
      'noConversations': '暂无对话',
      'noConversationsHint': '给其他会员发私信开始对话吧。',
      'typeMessage': '输入消息内容...',
      'send': '发送',
      'recipientNickname': '收件人昵称',
      'recipientNicknameHint': '输入昵称',
      'freeViewCountLabel': '免费观看次数',
      'sendMessageToUser': '发私信',
      'viewUserPosts': '查看帖子',
      'viewUserComments': '查看评论',
      'userPostsListTitleSelf': '帖子',
      'userPostsListTitleOther': '帖子',
      'userPostsListTitleOtherNamed': '{name}的帖子',
      'userPublicReviewsTitleNamed': '{name}的剧评',
      'userPostsTabPosts': '帖子',
      'userPostsEmptyPosts': '{name}还没有帖子。',
      'userPostsEmptyComments': '{name}还没有评论。',
      'userCommentsListTitle': '评论',
      'activityScore': '活跃度',
      'communityRanking': '社区排名',
      'seeMore': '更多',
      'watchedDramas': '我看过的剧',
      'noWatchedDramas': '还没有观看过的剧',
      'profileFavoritesTitle': 'FAVORITES',
      'profileFavoritesRemove': '从收藏移除',
      'profileFavoritesRemoveConfirm': '从收藏中移除此剧？',
      'favoriteActivityTitle': '{name}的收藏',
      'favoriteActivityHeaderTitle': '收藏',
      'favoriteActivityDiaryEmpty': '观影日记里还没有这部剧的观看记录。',
      'favoriteActivityReviewEmpty': '你还没有为这部剧写过剧评。',
      'profileRatingsTitle': 'RATINGS',
      'profileRatingsTitleOther': 'RATINGS',
      'profileRatingsCount': '{n} 条评分',
      'profileRatingsAverage': '平均',
    },
    'jp': {
      'searchHint': '何でも検索',
      'login': 'ログイン',
      'profile': 'プロフィール',
      'logout': 'ログアウト',
      'logoutSuccess': 'ログアウトしました',
      'settings': '設定',
      'language': '言語',
      'theme': 'テーマ',
      'themeLight': 'ライト',
      'themeDark': 'ダーク',
      'themeSystem': 'システム',
      'notificationSettings': '通知設定',
      'privacyPolicy': 'プライバシー',
      'helpCenter': 'ヘルプ',
      'myPosts': '投稿',
      'myPostBadge': '自分の',
      'myReviews': '私のレビュー',
      'myReviewsEmptyTitle': 'まだレビューがありません',
      'myReviewsEmptyHint': '作品詳細のレビュー欄から投稿できます。',
      'myReviewsSortTitle': '並べ替え',
      'myReviewsSortNewest': '新しい順',
      'myReviewsSortOldest': '古い順',
      'saved': '保存',
      'likes': 'いいね',
      'tabLikedPosts': '投稿',
      'tabLikedReviews': 'レビュー',
      'likesEmptyPosts': 'いいねした投稿はまだありません。',
      'likesEmptyReviews': 'いいねしたレビューはまだありません。',
      'likesEmptyComments': 'いいねしたコメントはまだありません。',
      'likesLoginRequired': 'ログインすると、いいねした投稿・レビュー・コメントをまとめて見られます。',
      'recentActivity': '最近のアクティビティ',
      'moreActivity': 'さらに表示',
      'profileRecentActivityEmpty': '評価したドラマはまだありません。評価するとここに表示されます。',
      'diary': 'ダイアリー',
      'diaryTitleWithName': '{name}のダイアリー',
      'diaryTitleWhenAnonymous': 'マイダイアリー',
      'diaryEmpty': 'まだ記録がありません。ショートで視聴すると日付ごとに表示されます。',
      'tabLists': 'リスト',
      'listsTitleWithName': '{name}のリスト',
      'listsFilmCount': '{n}',
      'listsCustomHint': '自分で作るリストは今後のアップデートで追加予定です。',
      'listsWatchlistDescription':
          '作品詳細の「見たい」で追加したタイトルです。タップでポスターグリッドを開きます。',
      'listsFilterSoon': 'リストの絞り込みは今後のアップデートで追加予定です。',
      'listCreateButton': 'リストを作成',
      'listCreateSuccess': 'リストを作成しました。',
      'listCreateTitle': 'リストを作成',
      'listCreateFieldTitle': 'タイトル',
      'listCreateFieldTitleHint': '例）ハラハラする復讐ドラマ',
      'listCreateFieldDescription': '説明',
      'listCreateFieldDescriptionHint': 'このリストの内容を説明してください。',
      'listCreateDramaCount': 'ドラマ（{count}/{max}）',
      'listCreateAddDrama': 'ドラマを追加',
      'listCreateNoDramaYet': 'まだドラマが追加されていません。',
      'listCreateSubmit': 'リストを作成',
      'listCreateSubmitting': '作成中...',
      'listCreateErrorNeedTitle': 'タイトルを1文字以上入力してください。',
      'listCreateErrorNeedDrama': 'ドラマを1つ以上追加してください。',
      'listCreateDuplicateDialogTitle': '追加済み',
      'listCreateErrorDuplicateDrama': 'このドラマはすでに追加されています。',
      'listCreateErrorMaxDrama': 'ドラマは最大20件まで追加できます。',
      'listCreateLoginRequired': 'ログインするとリストを作成できます。',
      'listCreateErrorSaveFailed': 'リストを保存できませんでした。もう一度お試しください。',
      'listDetailScreenTitle': 'リスト',
      'listEditTitle': 'リストを編集',
      'listEditSave': '保存',
      'listDeleteConfirmTitle': 'このリストを削除しますか？',
      'listDeleteConfirmMessage': '元に戻せません。プロフィールから削除されます。',
      'listDetailDeleteFailed': '削除できませんでした。もう一度お試しください。',
      'listDetailEmptyGrid': 'まだ作品が入っていません。',
      'listDetailLikePrompt': 'いいね？',
      'listDetailLikesSingular': 'いいね {n}',
      'listDetailLikesPlural': 'いいね {n}',
      'listCreateCoverTitle': 'リスト表紙（任意）',
      'listCreateCoverHint':
          'リストページ上部にのみ表示されます。ポスターやギャラリー(+)で2:3の切り取り画面が開きます。「なし」で解除できます。',
      'listCreateCoverNone': 'なし',
      'listCreateCoverGalleryPickFailed': 'ギャラリーを開けないか、画像を読み込めませんでした。',
      'listCreateCoverUploadFailed': '表紙画像をアップロードできませんでした。もう一度お試しください。',
      'listCreateCoverCropTitle': '表紙の範囲を調整',
      'listCreateCoverImageLoadFailed': '画像を読み込んで切り取れませんでした。',
      'listMultiPickApply': '追加 ({n})',
      'listMultiPickStepLimit': 'この画面では最大{n}件まで選べます。',
      'tabWatchlist': '見たい',
      'watchlistTitleWithName': '{name}の見たいリスト',
      'likesTitleWithName': '{name}のいいね',
      'tabSavedPosts': '保存した投稿',
      'watchlistEmptyTitle': 'まだ見たいリストに作品がありません',
      'watchlistEmptyPublic': 'まだ見たいリストに作品がありません',
      'watchlistRemoveTitle': 'リストから削除しますか？',
      'watchlistRemoveMessage': 'この作品を見たいリストから外します。',
      'dramaWatchlistAdd': '見たい',
      'dramaWatchlistRemove': 'リスト済み',
      'watchlistToastAdded': '見たいリストに追加しました。',
      'watchlistToastRemoved': '見たいリストから削除しました。',
      'watchlistLoginRequired': 'ログインすると見たいリストが使えます。',
      'dramaWatchHistoryTooltipAdd': '視聴済み',
      'dramaWatchHistoryTooltipRemove': '視聴履歴から削除',
      'watchHistoryToastAdded': '視聴履歴に追加しました。',
      'watchHistoryToastRemoved': '視聴履歴から削除しました。',
      'dramaSubpageConfirmWatchTitle': '視聴履歴に追加しますか？',
      'dramaSubpageConfirmWatchBody':
          'この作品はダイアリーの視聴履歴に表示されます。',
      'dramaSubpageConfirmWatchAlready': 'すでに視聴履歴にあります。',
      'dramaSubpageConfirmWatchlistTitle': '見たいリストに追加しますか？',
      'dramaSubpageConfirmWatchlistBody':
          'プロフィールの見たいリストに表示されます。',
      'dramaSubpageConfirmWatchlistAlready': 'すでに見たいリストにあります。',
      'dramaWatchlistSubpageBodyOn': '見たいリストに入っています。',
      'dramaWatchlistSubpageBodyOff': '右上の + から見たいリストに追加できます。',
      'dramaWatchActivitySheetTitle': '視聴を記録',
      'dramaWatchActivityWatchLabel': '視聴済',
      'dramaWatchActivityOptionalStars': '評価（任意）',
      'dramaWatchActivityReviewHint': 'レビュー（任意・先に評価を選んでください）',
      'dramaWatchActivityPosted': 'フィードに投稿しました。',
      'dramaWatchActivityLoginRequired': 'ログインしてから投稿できます。',
      'dramaWatchActivityWatchOrdinal1': '初視聴',
      'dramaWatchActivityWatchOrdinal2': '2回目の視聴',
      'dramaWatchActivityWatchOrdinal3': '3回目の視聴',
      'dramaWatchActivityWatchOrdinalN': '{n}回目の視聴',
      'dramaWatchActivityHeaderRating': '評価',
      'dramaWatchActivityHeaderReview': 'レビュー',
      'dramaBottomActionWatch': '視聴済',
      'dramaBottomActionRate': '評価',
      'dramaBottomActionReview': 'レビュー',
      'dramaBottomActionWatchlist': '見たい',
      'statsBarWatchersLabel': '視聴',
      'statsBarReviewsLabel': 'レビュー',
      'statsBarListsLabel': 'リスト',
      'statsBarFirstWatcher': '最初の視聴者に？',
      'statsBarWriteReview': 'レビューを書く',
      'statsBarMakeList': 'リストを作る',
      'statsBarComingSoon': '近日公開',
      'dramaReviewsTabPopular': '人気',
      'dramaReviewsTabAll': 'すべて',
      'dramaListsEmptyFeed': 'ドラマ一覧を読み込むとサンプルリストが表示されます。',
      'tagDramaListEmpty': 'このタグに一致する作品がまだありません。',
      'savedPostsEmptyTitle': '保存した投稿はまだありません',
      'savedPostsEmptyHint': 'コミュニティの投稿でブックマークを押すと保存できます。',
      'home': 'ホーム',
      'shorts': 'ショート',
      'popular': '人気',
      'freeBoard': '自由掲示板',
      'questionBoard': '質問掲示板',
      'welcomeLogin': 'DramaHubへ\nようこそ',
      'loginSubtitle': 'メールとパスワードを入力してください',
      'email': 'メール',
      'password': 'パスワード',
      'signUp': '会員登録',
      'noAccount': 'アカウントをお持ちでないですか？',
      'hasAccount': 'すでにアカウントをお持ちですか？',
      'welcomeSignup': 'DramaHubで\nつながろう',
      'signupSubtitle': '選択した言語でアプリが表示されます。同じ言語を選んだユーザーにだけ投稿が表示されます。',
      'country': '国',
      'nickname': 'ニックネーム',
      'nicknameHint': '他のユーザーに表示される名前',
      'passwordConfirm': 'パスワード確認',
      'signUpButton': '登録する',
      'popularPlaceholder': '人気',
      'freeBoardPlaceholder': '自由掲示板',
      'tabHot': '人気',
      'tabGeneral': '一般',
      'tabQnA': 'Q&A',
      'talkAskFeedLayoutSwitchToCards': 'カード表示',
      'talkAskFeedLayoutSwitchToList': 'リスト表示',
      'tabReviews': 'レビュー',
      'trendTabHint': 'いいね10以上または閲覧100以上の投稿が表示されます。',
      'reviewsTabEmpty': 'ドラマを検索して最初のレビューを投稿しましょう。',
      'spoilerBadge': 'ネタバレ',
      'reviewSpoilerDisclaimer': 'このレビューにはネタバレが含まれる場合があります。',
      'reviewSpoilerTapToRevealLetterboxd': 'このレビューにはネタバレが含まれる場合があります。タップで表示します。',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'letterboxdReviewDetailTabReview': 'レビュー',
      'letterboxdReviewDetailTabPostWithCount': 'コメント {n}',
      'letterboxdReviewDetailAppBarTitle': '{name}さんのレビュー',
      'letterboxdReviewWatchedLine': '視聴 {date}',
      'selectDrama': 'ドラマを検索',
      'reviewDramaSearchHint': 'ショートドラマを検索',
      'ratingLabel': '評価',
      'spoilerToggle': 'ネタバレを含む',
      'reviewNeedDramaRating': 'レビューにはドラマと星評価が必要です。',
      'reviewNeedDrama': 'レビューにはドラマを選択してください。',
      'reviewPleaseSelectRating': '星の評価を選んでください。',
      'search': '検索',
      'searchScopeTitleAndBody': 'タイトル+本文',
      'searchScopeTitle': 'タイトル',
      'searchScopeBody': '本文',
      'searchScopeComment': 'コメント',
      'searchScopeNickname': 'ニックネーム',
      'timeAgoJustNow': 'たった今',
      'timeAgoMinutes': '%d分前',
      'timeAgoHours': '%d時間前',
      'timeAgoDays': '%d日前',
      'timeAgoWeeks': '%d週間前',
      'timeAgoMonths': '%dヶ月前',
      'timeAgoYears': '%d年前',
      'searchCommunityHint': 'タイトル・本文・コメント・ニックネームで検索',
      'searchEnterQuery': '検索語を入力してください',
      'searchNoResults': '"%s"の検索結果はありません',
      'postSoon': '投稿はもうすぐここに表示されます',
      'shortsSoon': 'ショート動画はもうすぐここに表示されます',
      'loginSuccess': 'ログインしました',
      'loginWithGoogle': 'Googleでログイン',
      'loginDividerOr': 'または',
      'loginPreparing': 'ログイン準備中です',
      'signupPreparing': '会員登録ページ準備中です',
      'notReadyYet': '準備中です',
      'enterEmail': 'メールを入力してください',
      'validEmail': '有効なメール形式を入力してください',
      'enterPassword': 'パスワードを入力してください',
      'passwordMin': 'パスワードは8文字以上にしてください',
      'passwordSpecial': 'パスワードに特殊文字を1文字以上含めてください',
      'passwordHint': '8文字以上、特殊文字1文字以上',
      'passwordMismatch': 'パスワードが一致しません',
      'loginErrorWrongPassword': 'パスワードが違います。',
      'loginErrorEmailNotRegistered': 'このメールで登録されたアカウントがありません。',
      'loginErrorGeneric': 'ログインに失敗しました。もう一度お試しください。',
      'enterNickname': 'ニックネームを入力してください',
      'nicknameMin': 'ニックネームは2文字以上にしてください',
      'soon': 'もうすぐ',
      'share': '共有',
      'copyLink': 'リンクをコピー',
      'shareToApps': 'アプリで共有',
      'shareSettings': '共有設定',
      'linkCopied': 'リンクをコピーしました',
      'reviewShareImageFailed': '共有用画像を作成できませんでした。',
      'changeProfilePhoto': 'プロフィール写真を変更',
      'pickFromGallery': 'ギャラリーから選択',
      'removePhoto': '写真を削除',
      'profilePhotoUpdated': 'プロフィール写真を更新しました',
      'profilePhotoPreview': 'プレビュー',
      'edit': '編集',
      'edited': '編集済み',
      'delete': '削除',
      'report': '報告',
      'block': 'ブロック',
      'reportPostTitle': '報告',
      'reportPostMessage': 'この投稿を報告しますか？',
      'reportSubmitted': '報告を受け付けました。',
      'blockPostTitle': '投稿を非表示',
      'blockPostMessage': 'この投稿をフィードから非表示にしますか？',
      'blockPostDone': '投稿を非表示にしました。',
      'save': '保存',
      'done': '完了',
      'rotate': '回転',
      'drama': 'ドラマ',
      'review': 'レビュー',
      'notifications': '通知',
      'notificationsEmpty': '投稿へのコメント・返信・いいねがここに表示されます。',
      'dramaSearchHint': 'ドラマを検索...',
      'popularSearch': '人気の検索',
      'searchResults': '検索結果',
      'rankingEmpty': 'この期間はまだデータがありません。検索やタップでランキングが反映されます。',
      'periodDay': '今日',
      'periodWeek': '今週',
      'periodMonth': '今月',
      'periodYear': '今年',
      'recommended': 'おすすめ',
      'newReleases': '新作',
      'popularRanking': '人気ランキング',
      'dramaListTabAll': 'すべて',
      'category': 'カテゴリ',
      'genre': 'ジャンル',
      'target': '対象',
      'membershipExclusive': '会員限定',
      'dramaExclusive': 'DramaHub 独占',
      'rating': '評価',
      'participants': '参加',
      'ratingsAndComments': '評価・レビュー',
      'writeReview': 'レビューを書く',
      'writeReviewAction': 'レビューを書く >',
      'synopsis': 'あらすじ',
      'episodes': '話数',
      'totalEpisodes': '全%d話',
      'episodeLabel': '第%d話',
      'dramaViewCount': '%s 回視聴',
      'episodeReviewRaterCount': '（%d件の評価）',
      'episodeReviewAlreadyExists': 'この話にはすでにレビューを投稿しています。',
      'episodeReviewSaveFailed': 'レビューを保存できませんでした。もう一度お試しください。',
      'cast': 'キャスト',
      'noCastInfo': '出演情報がありません。',
      'firstReview': '最初のレビューを書いてみましょう！',
      'dramaSpotlightNoReviews': '—',
      'reviewComposerLikedHint': 'この作品が好き',
      'reviewComposerRepliesHint': '返信を許可',
      'leaveReview': 'レビューを書く',
      'dramaAllReviewsCta': 'すべてのレビュー >',
      'play': '再生',
      'similarDramas': '似た作品',
      'ratingHint': '評価してレビューを書く',
      'ratingInstruction': 'このドラマを評価してください',
      'reviewPlaceholder': 'レビューを書く',
      'reviewTagInputHint': 'タグを追加',
      'reviewPlaceholderLong': 'あらすじ・字幕・吹き替えなどについてのご意見をお聞かせください！',
      'submitReview': '投稿する',
      'submit': '送信',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'loginRequired': 'レビューを書くにはログインしてください',
      'reviewSubmitted': 'レビューを投稿しました！',
      'reviewUpdated': 'レビューを更新しました！',
      'deleteReviewConfirm': 'このレビューを削除しますか？',
      'ratingRequired': '評価を選択してください',
      'reviewMinLength': 'レビューは5文字以上入力してください',
      'joinConversation': 'コメントを追加…',
      'reply': '返信',
      'dislike': '嫌い',
      'comments': 'コメント',
      'sortByTime': '最新順',
      'sortByTop': 'おすすめ順',
      'commentBeFirst': '最初のコメントを書いてみましょう！',
      'commentWrite': 'コメントを書く',
      'writeComment': 'コメントを書く',
      'activityPoint': ' 活動度 +1)',
      'replySubmit': '返信する',
      'filter': 'フィルター',
      'sort': '並び替え',
      'expand': '開く',
      'collapse': '閉じる',
      'sortByLikes': 'いいね順',
      'sortByLatest': '最新順',
      'contentType': 'コンテンツタイプ',
      'all': 'すべて',
      'interactiveDrama': 'インタラクティブドラマ',
      'shortDrama': 'ショートドラマ',
      'reset': 'リセット',
      'apply': '適用',
      'tags': 'タグ',
      'ageGap': '年齢差',
      'reunion': '再会',
      'loveTriangle': '三角関係',
      'revenge': '復讐',
      'female': '女性',
      'male': '男性',
      'lgbtq': 'LGBTQ',
      'region': '地域',
      'regional': '地域',
      'usa': 'アメリカ',
      'asia': 'アジア',
      'dubbing': '吹き替え',
      'originalAudio': '原音',
      'dubbed': '吹き替え',
      'tooLate': 'もう遅い',
      'lostChild': '迷子',
      'affair': '不倫',
      'friendsToLovers': '友達から恋人へ',
      'harem': 'ハーレム',
      'salvation': '救済',
      'pregnancy': '妊娠',
      'enemyToLover': '敵から恋人へ',
      'destinedLover': '運命の恋人',
      'watchAd': '広告を視聴',
      'watchAdPlusOne': '広告を見て +1回',
      'freeViewCredits': '無料視聴',
      'watchAdToEarn': '広告視聴で無料視聴回数を獲得',
      'noCredits': '無料視聴回数がありません。広告を視聴してください。',
      'level': 'レベル',
      'memberLevel': '会員レベル',
      'points': 'pt',
      'levelInfo': 'レベル情報',
      'levelInfoSubtitle': '活動でポイントを貯めてレベルアップしましょう。',
      'currentLevel': '現在のレベル',
      'totalPointsLabel': '総Point',
      'nextLevelNeeded': '次のレベルまであと N',
      'entireLevelSystem': 'レベルシステム一覧',
      'levelSystemDescription': '各レベルに到達するために必要な累計ポイントです。',
      'attainmentPoint': '達成Point',
      'achievementStatus': '達成状況',
      'tableIcon': 'アイコン',
      'currentLevelLabel': '現在',
      'levelAchieved': '達成',
      'levelNotAchieved': '—',
      'writePost': '投稿する',
      'postTitle': 'タイトル',
      'postTitleHint': 'タイトルを入力',
      'postContent': '本文',
      'postContentHint': '自由に書いてみましょう',
      'postSubmit': '投稿',
      'postSubmitted': '投稿しました！',
      'postSaveFailed': '保存に失敗しました。もう一度お試しください。',
      'postSyncFailed': 'サーバーと同期できませんでした。ネットワーク確認のうえ更新してください。',
      'postEditSuccess': '更新しました。',
      'postEditFailed': '更新に失敗しました。もう一度お試しください。',
      'editPost': '投稿を編集',
      'deletePostConfirm': 'この投稿を削除しますか？',
      'addPhoto': '写真を追加',
      'titleRequired': 'タイトルを入力してください',
      'contentRequired': '内容を入力してください',
      'takePhoto': 'カメラで撮影',
      'pickFromFiles': 'ファイルから選択',
      'maxPhotos': '最大4枚まで',
      'titleMinLength': 'タイトルは2文字以上入力してください',
      'contentMinLength': '内容は10文字以上入力してください',
      'postCooldown': '3分後に再度投稿できます',
      'postLink': 'URL',
      'postLinkHint': 'https://...',
      'messages': 'メッセージ',
      'profilePublicUserUnavailable': 'プロフィールを読み込めませんでした。',
      'profileStatFollow': 'フォロー',
      'followScreenTitle': 'フォロー',
      'tabFollowing': 'フォロー中',
      'tabFollowers': 'フォロワー',
      'followEmptyFollowing': 'フォローしているアカウントはまだありません。',
      'followEmptyFollowers': 'フォロワーはまだいません。',
      'followButtonFollow': 'フォロー',
      'followButtonFollowing': 'フォロー中',
      'followUnfollow': 'フォロー解除',
      'loginRequiredForFollow': 'フォロー機能を使うにはログインしてください。',
      'networkPageTitle': '{name}のネットワーク',
      'userFollowTitleWithName': '{name}のフォロー',
      'followViewProfile': 'プロフィールを見る',
      'newMessage': '新規メッセージ',
      'noConversations': '会話はまだありません',
      'noConversationsHint': '会員にメッセージを送って会話を始めましょう。',
      'typeMessage': 'メッセージを入力...',
      'send': '送信',
      'recipientNickname': '宛先ニックネーム',
      'recipientNicknameHint': 'ニックネームを入力',
      'freeViewCountLabel': '無料視聴回数',
      'sendMessageToUser': 'メッセージを送る',
      'viewUserPosts': '投稿を見る',
      'viewUserComments': 'コメントを見る',
      'userPostsListTitleSelf': '投稿',
      'userPostsListTitleOther': '投稿',
      'userPostsListTitleOtherNamed': '{name}さんの投稿',
      'userPublicReviewsTitleNamed': '{name}さんのレビュー',
      'userPostsTabPosts': '投稿',
      'userPostsEmptyPosts': '{name}さんの投稿はまだありません。',
      'userPostsEmptyComments': '{name}さんのコメントはまだありません。',
      'userCommentsListTitle': 'コメント',
      'activityScore': 'ポイント',
      'communityRanking': 'コミュニティランキング',
      'seeMore': 'もっと見る',
      'watchedDramas': '視聴したドラマ',
      'noWatchedDramas': '視聴したドラマはありません',
      'profileFavoritesTitle': 'FAVORITES',
      'profileFavoritesRemove': 'お気に入りから削除',
      'profileFavoritesRemoveConfirm': 'このドラマをお気に入りから削除しますか？',
      'favoriteActivityTitle': '{name}のお気に入り',
      'favoriteActivityHeaderTitle': 'お気に入り',
      'favoriteActivityDiaryEmpty': 'この作品のダイアリー（視聴記録）がまだありません。',
      'favoriteActivityReviewEmpty': 'この作品のレビューはまだ書いていません。',
      'profileRatingsTitle': 'RATINGS',
      'profileRatingsTitleOther': 'RATINGS',
      'profileRatingsCount': '評価 {n}件',
      'profileRatingsAverage': '平均',
    },
  };

  String get(String key) => _map[key] ?? key;
}
