/// 국가별 앱 문자열 (US=영어, KR=한국어, CN=중국어, JP=일본어)
class AppStrings {
  AppStrings(this.country) : _map = _strings[country] ?? _strings['us']!;

  final String country;
  final Map<String, String> _map;

  static const _strings = {
    'us': {
      'searchHint': 'Search for anything',
      'login': 'Log in',
      'profile': 'Profile',
      'logout': 'Log out',
      'logoutSuccess': 'Logged out successfully',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'themeSystem': 'System',
      'notificationSettings': 'Notifications',
      'privacyPolicy': 'Privacy',
      'helpCenter': 'Help',
      'myPosts': 'My posts',
      'myPostBadge': 'my',
      'myReviews': 'My reviews',
      'saved': 'Saved',
      'home': 'Home',
      'shorts': 'Shorts',
      'popular': 'Popular',
      'freeBoard': 'TALK',
      'questionBoard': 'Ask',
      'welcomeLogin': 'Welcome to DramaHub',
      'loginSubtitle': 'Enter your email and password',
      'email': 'Email',
      'password': 'Password',
      'signUp': 'Sign up',
      'noAccount': "Don't have an account? ",
      'hasAccount': 'Already have an account? ',
      'welcomeSignup': 'Start connecting\nwith DramaHub',
      'signupSubtitle': 'The app will display in this language. Your posts will only be visible to users who selected the same language.',
      'country': 'Country',
      'nickname': 'Nickname',
      'nicknameHint': 'Name shown to other users',
      'passwordConfirm': 'Confirm password',
      'signUpButton': 'Sign up',
      'popularPlaceholder': 'Popular',
      'freeBoardPlaceholder': 'TALK',
      'tabHot': 'Trend',
      'tabGeneral': 'Talk',
      'tabQnA': 'Ask',
      'tabReviews': 'Reviews',
      'trendTabHint': 'Posts with 10+ likes or 100+ views appear here.',
      'reviewsTabEmpty': 'Search a drama and post the first review.',
      'spoilerBadge': 'Spoilers',
      'reviewSpoilerDisclaimer': 'Review may contain spoilers.',
      'reviewSpoilerTapToRevealLetterboxd': 'This review may contain spoilers. Tap to reveal.',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'selectDrama': 'Search drama',
      'reviewDramaSearchHint': 'Search short drama',
      'ratingLabel': 'Rating',
      'spoilerToggle': 'Contains spoilers',
      'reviewNeedDramaRating': 'Choose a drama and a star rating to post a review.',
      'reviewNeedDrama': 'Please select a drama for your review.',
      'reviewPleaseSelectRating': 'Please select a star rating.',
      'search': 'Search',
      'searchScopeTitleAndBody': 'Title+Content',
      'searchScopeTitle': 'Title',
      'searchScopeBody': 'Content',
      'searchScopeComment': 'Comment',
      'searchScopeNickname': 'Nickname',
      'timeAgoJustNow': 'Just now',
      'timeAgoMinutes': '%d min ago',
      'timeAgoHours': '%d hr ago',
      'timeAgoDays': '%d day ago',
      'timeAgoWeeks': '%d wk ago',
      'timeAgoMonths': '%d mo ago',
      'timeAgoYears': '%d yr ago',
      'searchCommunityHint': 'Search title, content, comments, nickname',
      'searchEnterQuery': 'Enter a search term',
      'searchNoResults': 'No results for "%s"',
      'postSoon': 'Posts will appear here soon',
      'shortsSoon': 'Short videos will appear here soon',
      'loginSuccess': 'Logged in successfully',
      'loginWithGoogle': 'Continue with Google',
      'loginPreparing': 'Login is being prepared',
      'signupPreparing': 'Sign up page is being prepared',
      'notReadyYet': 'Not ready yet.',
      'enterEmail': 'Please enter your email',
      'validEmail': 'Please enter a valid email',
      'enterPassword': 'Please enter your password',
      'passwordMin': 'Password must be at least 8 characters',
      'passwordSpecial': 'Password must contain at least one special character',
      'passwordHint': '8+ characters, at least 1 special character',
      'passwordMismatch': 'Passwords do not match',
      'loginErrorWrongPassword': 'Wrong password.',
      'loginErrorEmailNotRegistered': 'No account found with this email.',
      'loginErrorGeneric': 'Login failed. Please try again.',
      'enterNickname': 'Please enter a nickname',
      'nicknameMin': 'Nickname must be at least 2 characters',
      'soon': 'Soon',
      'share': 'Share',
      'copyLink': 'Copy link',
      'shareToApps': 'Share to apps',
      'shareSettings': 'Share settings',
      'linkCopied': 'Link copied',
      'changeProfilePhoto': 'Change profile photo',
      'pickFromGallery': 'Choose from gallery',
      'removePhoto': 'Remove photo',
      'profilePhotoUpdated': 'Profile photo updated',
      'profilePhotoPreview': 'Preview',
      'edit': 'Edit',
      'edited': 'Edited',
      'delete': 'Delete',
      'report': 'Report',
      'block': 'Block',
      'reportPostTitle': 'Report',
      'reportPostMessage': 'Report this post?',
      'reportSubmitted': 'Report submitted.',
      'blockPostTitle': 'Block post',
      'blockPostMessage': 'Hide this post from your feed?',
      'blockPostDone': 'Post hidden.',
      'save': 'Save',
      'done': 'Done',
      'rotate': 'Rotate',
      'drama': 'Drama',
      'review': 'Review',
      'notifications': 'Alerts',
      'notificationsEmpty': 'Comments, replies and likes on your posts will appear here.',
      'dramaSearchHint': 'Search dramas...',
      'popularSearch': 'People are searching',
      'searchResults': 'Search results',
      'rankingEmpty': 'No data for this period yet. Search or tap items to build the ranking.',
      'periodDay': 'Today',
      'periodWeek': 'Week',
      'periodMonth': 'Month',
      'periodYear': 'Year',
      'recommended': 'Recommended',
      'newReleases': 'New',
      'popularRanking': 'Popular',
      'category': 'Category',
      'genre': 'Genre',
      'target': 'Target',
      'membershipExclusive': 'Membership',
      'dramaExclusive': 'DramaHub Exclusive',
      'rating': 'Rating',
      'participants': 'ratings',
      'ratingsAndComments': 'Ratings & Reviews',
      'writeReview': 'Write a review',
      'writeReviewAction': 'Write a review >',
      'synopsis': 'Synopsis',
      'episodes': 'Episodes',
      'totalEpisodes': 'Total %d eps',
      'episodeLabel': 'Ep %d',
      'dramaViewCount': '%s views',
      'episodeReviewRaterCount': '(%d ratings)',
      'episodeReviewAlreadyExists': 'You already left a review for this episode.',
      'episodeReviewSaveFailed': 'Could not save your review. Please try again.',
      'cast': 'Cast',
      'noCastInfo': 'No cast info available.',
      'firstReview': 'Be the first to write a review!',
      'reviewComposerLikedHint': 'Liked this drama',
      'reviewComposerRepliesHint': 'Allow replies on this review',
      'leaveReview': 'Leave a Review',
      'play': 'Play',
      'similarDramas': 'Similar',
      'ratingHint': 'Rate and write a review',
      'ratingInstruction': 'Rate this drama',
      'reviewPlaceholder': 'Write your review',
      'reviewTagInputHint': 'Add tags',
      'reviewPlaceholderLong': 'Please leave various opinions on plot, subtitles, dubbing, etc!',
      'submitReview': 'Submit',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'ok': 'OK',
      'loginRequired': 'Please log in to write a review',
      'reviewSubmitted': 'Review submitted!',
      'reviewUpdated': 'Review updated!',
      'deleteReviewConfirm': 'Delete this review?',
      'ratingRequired': 'Please select a rating',
      'reviewMinLength': 'Please write at least 5 characters',
      'joinConversation': 'Add a comment…',
      'reply': 'Reply',
      'likes': 'Likes',
      'dislike': 'Dislike',
      'comments': 'Comments',
      'sortByTime': 'Time',
      'sortByTop': 'Top',
      'commentBeFirst': 'Be the first to comment!',
      'commentWrite': 'Post comment',
      'writeComment': 'Write a comment',
      'activityPoint': ' Activity +1)',
      'replySubmit': 'Post',
      'filter': 'Filter',
      'sort': 'Sort',
      'sortByLikes': 'Most liked',
      'sortByLatest': 'Latest',
      'contentType': 'Content type',
      'all': 'All',
      'interactiveDrama': 'Interactive drama',
      'shortDrama': 'Short drama',
      'reset': 'Reset',
      'apply': 'Apply',
      'tags': 'Tags',
      'ageGap': 'Age gap',
      'reunion': 'Reunion',
      'loveTriangle': 'Love triangle',
      'revenge': 'Revenge',
      'female': 'Female',
      'male': 'Male',
      'lgbtq': 'LGBTQ',
      'region': 'Region',
      'regional': 'Regional',
      'usa': 'USA',
      'asia': 'Asia',
      'dubbing': 'Dubbing',
      'originalAudio': 'Original',
      'dubbed': 'Dubbed',
      'tooLate': 'Too late',
      'lostChild': 'Lost child',
      'affair': 'Affair',
      'friendsToLovers': 'Friends to lovers',
      'harem': 'Harem',
      'salvation': 'Salvation',
      'pregnancy': 'Pregnancy',
      'enemyToLover': 'Enemy to lover',
      'destinedLover': 'Destined lover',
      'watchAd': 'Watch ad',
      'watchAdPlusOne': 'Watch ad +1',
      'freeViewCredits': 'Free views',
      'watchAdToEarn': 'Watch ad to earn free views',
      'noCredits': 'No free views. Watch an ad to earn.',
      'level': 'Level',
      'memberLevel': 'Member level',
      'points': 'pts',
      'levelInfo': 'Level Info',
      'levelInfoSubtitle': 'Earn points through activity to level up.',
      'currentLevel': 'Current Level',
      'totalPointsLabel': 'Total Points',
      'nextLevelNeeded': 'N needed for next level',
      'entireLevelSystem': 'Entire Level System',
      'levelSystemDescription': 'Total points required to reach each level.',
      'attainmentPoint': 'Attainment Point',
      'achievementStatus': 'Status',
      'tableIcon': 'Icon',
      'currentLevelLabel': 'Current',
      'levelAchieved': 'Achieved',
      'levelNotAchieved': '—',
      'writePost': 'Write post',
      'postTitle': 'Title',
      'postTitleHint': 'Give your post a title',
      'postContent': 'Content',
      'postContentHint': 'What do you want to share?',
      'postSubmit': 'Post',
      'postSubmitted': 'Posted!',
      'postSaveFailed': 'Save failed. Please try again.',
      'postSyncFailed': 'Couldn\'t sync to server. Check network and refresh.',
      'postEditSuccess': 'Updated.',
      'postEditFailed': 'Update failed. Please try again.',
      'editPost': 'Edit post',
      'deletePostConfirm': 'Delete this post?',
      'addPhoto': 'Add photo',
      'titleRequired': 'Please enter a title',
      'contentRequired': 'Please enter some content',
      'takePhoto': 'Take photo',
      'pickFromFiles': 'Browse files',
      'maxPhotos': 'Up to 4 photos',
      'titleMinLength': 'Title must be at least 2 characters',
      'contentMinLength': 'Content must be at least 10 characters',
      'postCooldown': 'You can post again in 3 minutes',
      'postLink': 'URL',
      'postLinkHint': 'https://...',
      'messages': 'Messages',
      'profileStatFollow': 'Follow',
      'followScreenTitle': 'Follow',
      'tabFollowing': 'Following',
      'tabFollowers': 'Followers',
      'followEmptyFollowing': 'You are not following anyone yet.',
      'followEmptyFollowers': 'No followers yet.',
      'followButtonFollow': 'Follow',
      'followButtonFollowing': 'Following',
      'followUnfollow': 'Unfollow',
      'loginRequiredForFollow': 'Sign in to use follow.',
      'networkPageTitle': "{name}'s Network",
      'followViewProfile': 'View profile',
      'newMessage': 'New message',
      'noConversations': 'No conversations yet',
      'noConversationsHint': 'Send a message to another member to start.',
      'typeMessage': 'Type a message...',
      'send': 'Send',
      'recipientNickname': 'Recipient nickname',
      'recipientNicknameHint': 'Enter nickname',
      'freeViewCountLabel': 'Free view count',
      'sendMessageToUser': 'Send message',
      'viewUserPosts': 'View posts',
      'viewUserComments': 'View comments',
      'activityScore': 'Points',
      'communityRanking': 'Community ranking',
      'seeMore': 'more',
      'watchedDramas': 'Watched dramas',
      'noWatchedDramas': 'You haven\'t watched any dramas.',
    },
    'kr': {
      'searchHint': '무엇이든 찾아보세요',
      'login': '로그인',
      'profile': '프로필',
      'logout': '로그아웃',
      'logoutSuccess': '로그아웃되었습니다',
      'settings': '설정',
      'language': '언어',
      'theme': '테마',
      'themeLight': '라이트',
      'themeDark': '다크',
      'themeSystem': '시스템',
      'notificationSettings': '알림 설정',
      'privacyPolicy': '개인정보 처리방침',
      'helpCenter': '고객센터',
      'myPosts': '내가 쓴 글',
      'myPostBadge': '내 글',
      'myReviews': '내가 쓴 리뷰',
      'saved': '저장',
      'home': '홈',
      'shorts': '숏폼',
      'popular': '인기글',
      'freeBoard': '자유게시판',
      'questionBoard': '질문게시판',
      'welcomeLogin': 'DramaHub에 오신 것을\n환영합니다',
      'loginSubtitle': '이메일과 비밀번호를 입력해주세요',
      'email': '이메일',
      'password': '비밀번호',
      'signUp': '회원가입',
      'noAccount': '계정이 없으신가요? ',
      'hasAccount': '이미 계정이 있으신가요? ',
      'welcomeSignup': 'DramaHub와 함께\n소통해보세요',
      'signupSubtitle': '선택한 언어로 앱이 표시됩니다. 같은 언어를 선택한 사용자에게만 글이 보입니다.',
      'country': '국가',
      'nickname': '닉네임',
      'nicknameHint': '다른 사용자에게 보여질 이름',
      'passwordConfirm': '비밀번호 확인',
      'signUpButton': '가입하기',
      'popularPlaceholder': '인기글',
      'freeBoardPlaceholder': '자유게시판',
      'tabHot': '트렌드',
      'tabGeneral': '자유',
      'tabQnA': '질문',
      'tabReviews': '리뷰',
      'trendTabHint': '좋아요 10개 이상 또는 조회수 100 이상인 글이 표시돼요.',
      'reviewsTabEmpty': '드라마를 검색해 첫 리뷰를 남겨 보세요.',
      'spoilerBadge': '스포일러 포함',
      'reviewSpoilerDisclaimer': '리뷰에 스포일러가 포함될 수 있습니다.',
      'reviewSpoilerTapToRevealLetterboxd': '스포일러가 포함될 수 있어요. 탭하면 본문이 공개됩니다.',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'selectDrama': '드라마 검색',
      'reviewDramaSearchHint': '숏드라마 검색',
      'ratingLabel': '별점',
      'spoilerToggle': '스포일러가 포함되어 있어요',
      'reviewNeedDramaRating': '리뷰를 등록하려면 드라마와 별점을 선택해 주세요.',
      'reviewNeedDrama': '리뷰를 등록하려면 드라마를 선택해 주세요.',
      'reviewPleaseSelectRating': '별점을 선택해 주세요.',
      'search': '검색',
      'searchScopeTitleAndBody': '제목+내용',
      'searchScopeTitle': '제목',
      'searchScopeBody': '내용',
      'searchScopeComment': '댓글',
      'searchScopeNickname': '닉네임',
      'timeAgoJustNow': '방금 전',
      'timeAgoMinutes': '%d분 전',
      'timeAgoHours': '%d시간 전',
      'timeAgoDays': '%d일 전',
      'timeAgoWeeks': '%d주 전',
      'timeAgoMonths': '%d개월 전',
      'timeAgoYears': '%d년 전',
      'searchCommunityHint': '제목, 내용, 댓글, 닉네임 검색',
      'searchEnterQuery': '검색어를 입력해 주세요',
      'searchNoResults': '"%s" 검색 결과가 없어요',
      'postSoon': '곧 게시글이 여기에 표시됩니다',
      'shortsSoon': '곧 숏폼 영상이 여기에 표시됩니다',
      'loginSuccess': '로그인했습니다',
      'loginWithGoogle': 'Google로 로그인',
      'loginPreparing': '로그인 준비 중입니다',
      'signupPreparing': '회원가입 페이지 준비 중입니다',
      'notReadyYet': '아직 준비 중입니다',
      'enterEmail': '이메일을 입력해주세요',
      'validEmail': '올바른 이메일 형식을 입력해주세요',
      'enterPassword': '비밀번호를 입력해주세요',
      'passwordMin': '비밀번호는 8자 이상이어야 합니다',
      'passwordSpecial': '비밀번호에 특수문자를 1개 이상 포함해주세요',
      'passwordHint': '8자 이상, 특수문자 1개 이상',
      'passwordMismatch': '비밀번호가 일치하지 않습니다',
      'loginErrorWrongPassword': '비밀번호가 틀렸어요.',
      'loginErrorEmailNotRegistered': '가입된 이메일이 없어요.',
      'loginErrorGeneric': '로그인에 실패했어요. 다시 시도해 주세요.',
      'enterNickname': '닉네임을 입력해주세요',
      'nicknameMin': '닉네임은 2자 이상이어야 합니다',
      'soon': '곧',
      'share': '공유',
      'copyLink': '링크 복사',
      'shareToApps': '앱으로 공유',
      'shareSettings': '공유 설정',
      'linkCopied': '링크가 복사되었습니다',
      'changeProfilePhoto': '프로필 사진 변경',
      'pickFromGallery': '갤러리에서 선택',
      'removePhoto': '사진 삭제',
      'profilePhotoUpdated': '프로필 사진이 변경되었어요',
      'profilePhotoPreview': '미리 보기',
      'edit': '수정',
      'edited': '수정됨',
      'delete': '삭제',
      'report': '신고하기',
      'block': '차단',
      'reportPostTitle': '신고하기',
      'reportPostMessage': '이 게시글을 신고하시겠습니까?',
      'reportSubmitted': '신고가 접수되었습니다.',
      'blockPostTitle': '글 차단',
      'blockPostMessage': '이 글을 피드에서 숨기시겠습니까?',
      'blockPostDone': '해당 글을 차단했습니다.',
      'save': '저장',
      'done': '완료',
      'rotate': '회전',
      'drama': '드라마',
      'review': '리뷰',
      'notifications': '알림',
      'notificationsEmpty': '내가 쓴 글에 댓글·대댓글·좋아요가 오면 여기에 표시됩니다.',
      'dramaSearchHint': '드라마 검색...',
      'popularSearch': '인기 검색',
      'searchResults': '검색 결과',
      'rankingEmpty': '이 기간에 아직 데이터가 없어요. 검색하거나 항목을 눌러보면 순위가 쌓여요.',
      'periodDay': '오늘',
      'periodWeek': '이번 주',
      'periodMonth': '이번 달',
      'periodYear': '올해',
      'recommended': '추천',
      'newReleases': '신작',
      'popularRanking': '인기 순위',
      'category': '카테고리',
      'genre': '장르',
      'target': '대상',
      'membershipExclusive': '멤버십 전용',
      'dramaExclusive': 'DramaHub 전용',
      'rating': '평점',
      'participants': '참여',
      'ratingsAndComments': '평점 & 리뷰',
      'writeReview': '리뷰 작성하기',
      'writeReviewAction': '리뷰 작성하기 >',
      'synopsis': '줄거리',
      'episodes': '회차',
      'totalEpisodes': '총 %d편',
      'episodeLabel': '%d화',
      'dramaViewCount': '%s 조회수',
      'episodeReviewRaterCount': '(%d명 참여)',
      'episodeReviewAlreadyExists': '이미 이 회차에 리뷰를 작성했습니다.',
      'episodeReviewSaveFailed': '리뷰를 저장하지 못했습니다. 다시 시도해 주세요.',
      'cast': '배우',
      'noCastInfo': '출연 정보가 없습니다.',
      'firstReview': '가장 먼저 리뷰를 작성해 보세요!',
      'reviewComposerLikedHint': '이 작품이 좋았어요',
      'reviewComposerRepliesHint': '댓글 허용',
      'leaveReview': '리뷰 남기기',
      'play': '재생',
      'similarDramas': '비슷한 작품',
      'ratingHint': '"이 작품, 당신은 몇 점?"',
      'ratingInstruction': '평점을 매겨 주세요',
      'reviewPlaceholder': '리뷰 작성하기',
      'reviewTagInputHint': '태그 추가',
      'reviewPlaceholderLong': '줄거리·자막·더빙 등에 대한 다양한 의견을 남겨주세요!',
      'submitReview': '등록하기',
      'submit': '등록',
      'cancel': '취소',
      'ok': '확인',
      'loginRequired': '리뷰를 쓰려면 로그인해주세요',
      'reviewSubmitted': '리뷰가 등록되었습니다!',
      'reviewUpdated': '리뷰가 수정되었습니다!',
      'deleteReviewConfirm': '이 리뷰를 삭제할까요?',
      'ratingRequired': '평점을 매겨 주세요',
      'reviewMinLength': '리뷰는 5자 이상 입력해 주세요',
      'joinConversation': '댓글을 입력하세요…',
      'reply': '답글',
      'likes': '좋아요',
      'dislike': '싫어요',
      'comments': '댓글',
      'sortByTime': '시간순',
      'sortByTop': '추천순',
      'commentBeFirst': '가장 먼저 댓글을 남겨보세요!',
      'commentWrite': '댓글 남기기',
      'writeComment': '댓글 쓰기',
      'activityPoint': ' 활동지수 +1)',
      'replySubmit': '답글 달기',
      'filter': '필터',
      'sort': '정렬',
      'sortByLikes': '좋아요 순',
      'sortByLatest': '최신순',
      'contentType': '콘텐츠 유형',
      'all': '모두',
      'interactiveDrama': '인터랙티브 드라마',
      'shortDrama': '숏폼 드라마',
      'reset': '초기화',
      'apply': '적용',
      'tags': '태그',
      'ageGap': '나이차',
      'reunion': '재회',
      'loveTriangle': '삼각관계',
      'revenge': '복수',
      'female': '여성',
      'male': '남성',
      'lgbtq': 'LGBTQ',
      'region': '지역',
      'regional': '지역',
      'usa': '미국',
      'asia': '아시아',
      'dubbing': '더빙',
      'originalAudio': '원음',
      'dubbed': '더빙',
      'tooLate': '이미 늦음',
      'lostChild': '길 잃은 어린이',
      'affair': '불륜',
      'friendsToLovers': '친구에서 연인으로',
      'harem': '하렘',
      'salvation': '구원',
      'pregnancy': '임신',
      'enemyToLover': '적에서 연인으로',
      'destinedLover': '운명적인 연인',
      'watchAd': '광고 시청',
      'watchAdPlusOne': '광고 보고 +1회',
      'freeViewCredits': '무료 시청',
      'watchAdToEarn': '광고 시청으로 무료 시청 횟수 획득',
      'noCredits': '무료 시청 횟수가 없어요. 광고를 시청해보세요.',
      'level': '레벨',
      'memberLevel': '회원레벨',
      'points': '점',
      'levelInfo': '레벨 정보',
      'levelInfoSubtitle': '활동으로 포인트를 쌓아 레벨을 올려보세요.',
      'currentLevel': '현재 레벨',
      'totalPointsLabel': '총 Point',
      'nextLevelNeeded': '다음 레벨까지 N 필요',
      'entireLevelSystem': '전체 레벨 시스템',
      'levelSystemDescription': '각 레벨에 도달하기 위해 필요한 총 포인트입니다.',
      'attainmentPoint': '도달 Point',
      'achievementStatus': '달성 여부',
      'tableIcon': '아이콘',
      'currentLevelLabel': '현재',
      'levelAchieved': '달성',
      'levelNotAchieved': '—',
      'writePost': '글쓰기',
      'postTitle': '제목',
      'postTitleHint': '제목을 입력하세요',
      'postContent': '내용',
      'postContentHint': '자유롭게 작성해보세요',
      'postSubmit': '등록',
      'postSubmitted': '등록되었어요!',
      'postSaveFailed': '저장에 실패했어요. 다시 시도해주세요.',
      'postSyncFailed': '서버 동기화에 실패했어요. 네트워크 확인 후 새로고침해주세요.',
      'postEditSuccess': '수정되었어요.',
      'postEditFailed': '수정에 실패했어요. 다시 시도해주세요.',
      'editPost': '글 수정',
      'deletePostConfirm': '이 글을 삭제할까요?',
      'addPhoto': '사진 추가',
      'titleRequired': '제목을 입력해주세요',
      'contentRequired': '내용을 입력해주세요',
      'takePhoto': '카메라로 촬영',
      'pickFromFiles': '파일에서 선택',
      'maxPhotos': '최대 4장까지',
      'titleMinLength': '제목은 2자 이상 입력해주세요',
      'contentMinLength': '내용은 10자 이상 입력해주세요',
      'postCooldown': '3분 후에 다시 글을 쓸 수 있어요',
      'postLink': '링크',
      'postLinkHint': 'https://...',
      'messages': '쪽지',
      'profileStatFollow': '팔로우',
      'followScreenTitle': '팔로우',
      'tabFollowing': '팔로잉',
      'tabFollowers': '팔로워',
      'followEmptyFollowing': '팔로우한 계정이 없어요.',
      'followEmptyFollowers': '아직 팔로워가 없어요.',
      'followButtonFollow': '팔로우',
      'followButtonFollowing': '팔로잉',
      'followUnfollow': '팔로우 취소',
      'loginRequiredForFollow': '팔로우를 사용하려면 로그인해 주세요.',
      'networkPageTitle': '{name}님의 네트워크',
      'followViewProfile': '프로필 보기',
      'newMessage': '새 쪽지',
      'noConversations': '대화가 없습니다',
      'noConversationsHint': '회원에게 쪽지를 보내 대화를 시작해보세요.',
      'typeMessage': '쪽지 내용 입력...',
      'send': '보내기',
      'recipientNickname': '받는 사람 닉네임',
      'recipientNicknameHint': '닉네임 입력',
      'freeViewCountLabel': '무료 시청 횟수',
      'sendMessageToUser': '쪽지 보내기',
      'viewUserPosts': '작성글 보기',
      'viewUserComments': '작성댓글 보기',
      'activityScore': '활동지수',
      'communityRanking': '커뮤니티 랭킹',
      'seeMore': '더보기',
      'watchedDramas': '내가 본 드라마',
      'noWatchedDramas': '시청한 드라마가 없어요',
    },
    'cn': {
      'searchHint': '搜索任何内容',
      'login': '登录',
      'profile': '个人资料',
      'logout': '退出登录',
      'logoutSuccess': '已退出登录',
      'settings': '设置',
      'language': '语言',
      'theme': '主题',
      'themeLight': '浅色',
      'themeDark': '深色',
      'themeSystem': '跟随系统',
      'notificationSettings': '通知设置',
      'privacyPolicy': '隐私政策',
      'helpCenter': '帮助中心',
      'myPosts': '我的帖子',
      'myPostBadge': '我的',
      'myReviews': '我写的评论',
      'saved': '收藏',
      'home': '首页',
      'shorts': '短视频',
      'popular': '热门',
      'freeBoard': '自由讨论',
      'questionBoard': '问答板',
      'welcomeLogin': '欢迎来到\nDramaHub',
      'loginSubtitle': '请输入邮箱和密码',
      'email': '邮箱',
      'password': '密码',
      'signUp': '注册',
      'noAccount': '还没有账号？',
      'hasAccount': '已有账号？',
      'welcomeSignup': '与DramaHub一起\n交流吧',
      'signupSubtitle': '应用将以此语言显示。您的帖子仅对选择相同语言的用户可见。',
      'country': '国家',
      'nickname': '昵称',
      'nicknameHint': '其他用户看到的名称',
      'passwordConfirm': '确认密码',
      'signUpButton': '注册',
      'popularPlaceholder': '热门',
      'freeBoardPlaceholder': '自由讨论',
      'tabHot': '热门',
      'tabGeneral': '综合',
      'tabQnA': '问答',
      'tabReviews': '剧评',
      'trendTabHint': '点赞≥10或浏览≥100的帖子会显示在这里。',
      'reviewsTabEmpty': '搜索剧集并发布第一条剧评。',
      'spoilerBadge': '含剧透',
      'reviewSpoilerDisclaimer': '本评论可能含有剧透。',
      'reviewSpoilerTapToRevealLetterboxd': '本剧评可能含有剧透。点击显示正文。',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'selectDrama': '搜索剧集',
      'reviewDramaSearchHint': '搜索短剧',
      'ratingLabel': '评分',
      'spoilerToggle': '含剧透内容',
      'reviewNeedDramaRating': '发布剧评前请选择剧集和星级。',
      'reviewNeedDrama': '发布剧评前请选择剧集。',
      'reviewPleaseSelectRating': '请选择星级。',
      'search': '搜索',
      'searchScopeTitleAndBody': '标题+内容',
      'searchScopeTitle': '标题',
      'searchScopeBody': '内容',
      'searchScopeComment': '评论',
      'searchScopeNickname': '昵称',
      'timeAgoJustNow': '刚刚',
      'timeAgoMinutes': '%d分钟前',
      'timeAgoHours': '%d小时前',
      'timeAgoDays': '%d天前',
      'timeAgoWeeks': '%d周前',
      'timeAgoMonths': '%d个月前',
      'timeAgoYears': '%d年前',
      'searchCommunityHint': '搜索标题、内容、评论、昵称',
      'searchEnterQuery': '请输入搜索词',
      'searchNoResults': '没有找到"%s"的结果',
      'postSoon': '帖子将很快显示在这里',
      'shortsSoon': '短视频将很快显示在这里',
      'loginSuccess': '登录成功',
      'loginWithGoogle': '使用Google登录',
      'loginPreparing': '登录功能准备中',
      'signupPreparing': '注册页面准备中',
      'notReadyYet': '功能准备中',
      'enterEmail': '请输入邮箱',
      'validEmail': '请输入有效的邮箱格式',
      'enterPassword': '请输入密码',
      'passwordMin': '密码至少8个字符',
      'passwordSpecial': '密码至少包含1个特殊字符',
      'passwordHint': '8个字符以上，至少1个特殊字符',
      'passwordMismatch': '两次密码不一致',
      'loginErrorWrongPassword': '密码错误。',
      'loginErrorEmailNotRegistered': '没有找到该邮箱的账号。',
      'loginErrorGeneric': '登录失败，请重试。',
      'enterNickname': '请输入昵称',
      'nicknameMin': '昵称至少2个字符',
      'soon': '即将',
      'share': '分享',
      'copyLink': '复制链接',
      'shareToApps': '分享到应用',
      'shareSettings': '分享设置',
      'linkCopied': '链接已复制',
      'changeProfilePhoto': '更换头像',
      'pickFromGallery': '从相册选择',
      'removePhoto': '删除照片',
      'profilePhotoUpdated': '头像已更新',
      'profilePhotoPreview': '预览',
      'edit': '编辑',
      'edited': '已编辑',
      'delete': '删除',
      'report': '举报',
      'block': '屏蔽',
      'reportPostTitle': '举报',
      'reportPostMessage': '确定举报此帖？',
      'reportSubmitted': '举报已提交。',
      'blockPostTitle': '屏蔽帖子',
      'blockPostMessage': '在动态中隐藏此帖？',
      'blockPostDone': '已屏蔽该帖。',
      'save': '保存',
      'done': '完成',
      'rotate': '旋转',
      'drama': '剧集',
      'review': '评论',
      'notifications': '通知',
      'notificationsEmpty': '您收到的评论、回复和点赞将显示在这里。',
      'dramaSearchHint': '搜索剧集...',
      'popularSearch': '热门搜索',
      'searchResults': '搜索结果',
      'rankingEmpty': '该时段暂无数据。搜索或点击作品后会出现排名。',
      'periodDay': '今天',
      'periodWeek': '本周',
      'periodMonth': '本月',
      'periodYear': '今年',
      'recommended': '推荐',
      'newReleases': '新作',
      'popularRanking': '人气排行',
      'category': '分类',
      'genre': '类型',
      'target': '受众',
      'membershipExclusive': '会员专享',
      'dramaExclusive': 'DramaHub 独家',
      'rating': '评分',
      'participants': '参与',
      'ratingsAndComments': '评分与评论',
      'writeReview': '写评论',
      'writeReviewAction': '写评论 >',
      'synopsis': '剧情简介',
      'episodes': '集数',
      'totalEpisodes': '共%d集',
      'episodeLabel': '第%d集',
      'dramaViewCount': '%s 次观看',
      'episodeReviewRaterCount': '（%d 人评分）',
      'episodeReviewAlreadyExists': '您已为本集留下评论。',
      'episodeReviewSaveFailed': '评论保存失败，请重试。',
      'cast': '演员',
      'noCastInfo': '暂无演员信息。',
      'firstReview': '来写第一条评论吧！',
      'reviewComposerLikedHint': '喜欢这部剧',
      'reviewComposerRepliesHint': '允许评论',
      'leaveReview': '留下评论',
      'play': '播放',
      'similarDramas': '类似作品',
      'ratingHint': '评分并写评论',
      'ratingInstruction': '请为这部剧评分',
      'reviewPlaceholder': '撰写剧评',
      'reviewTagInputHint': '添加标签',
      'reviewPlaceholderLong': '请分享对剧情、字幕、配音等的各种看法！',
      'submitReview': '提交',
      'submit': '提交',
      'cancel': '取消',
      'ok': '确定',
      'loginRequired': '请登录后再写评论',
      'reviewSubmitted': '评论已提交！',
      'reviewUpdated': '评论已修改！',
      'deleteReviewConfirm': '确定删除此评论？',
      'ratingRequired': '请选择评分',
      'reviewMinLength': '请输入至少5个字的评论',
      'joinConversation': '添加评论…',
      'reply': '回复',
      'likes': '赞',
      'dislike': '踩',
      'comments': '评论',
      'sortByTime': '时间',
      'sortByTop': '推荐',
      'commentBeFirst': '来写第一条评论吧！',
      'commentWrite': '写评论',
      'writeComment': '写评论',
      'activityPoint': ' 活跃度 +1)',
      'replySubmit': '发布',
      'filter': '筛选',
      'sort': '排序',
      'sortByLikes': '按赞数',
      'sortByLatest': '最新',
      'contentType': '内容类型',
      'all': '全部',
      'interactiveDrama': '互动剧',
      'shortDrama': '短剧',
      'reset': '重置',
      'apply': '应用',
      'tags': '标签',
      'ageGap': '年龄差',
      'reunion': '重逢',
      'loveTriangle': '三角恋',
      'revenge': '复仇',
      'female': '女性',
      'male': '男性',
      'lgbtq': 'LGBTQ',
      'region': '地区',
      'regional': '地区',
      'usa': '美国',
      'asia': '亚洲',
      'dubbing': '配音',
      'originalAudio': '原音',
      'dubbed': '配音',
      'tooLate': '为时已晚',
      'lostChild': '迷路的孩子',
      'affair': '婚外情',
      'friendsToLovers': '朋友变恋人',
      'harem': '后宫',
      'salvation': '救赎',
      'pregnancy': '怀孕',
      'enemyToLover': '敌人变恋人',
      'destinedLover': '命中注定的恋人',
      'watchAd': '观看广告',
      'watchAdPlusOne': '观看广告 +1次',
      'freeViewCredits': '免费观看',
      'watchAdToEarn': '观看广告获得免费观看次数',
      'noCredits': '没有免费观看次数。请观看广告。',
      'level': '等级',
      'memberLevel': '会员等级',
      'points': '分',
      'levelInfo': '等级信息',
      'levelInfoSubtitle': '通过活动积累积分提升等级。',
      'currentLevel': '当前等级',
      'totalPointsLabel': '总积分',
      'nextLevelNeeded': '距下一级还需 N',
      'entireLevelSystem': '等级体系',
      'levelSystemDescription': '达到各等级所需累计积分。',
      'attainmentPoint': '达成积分',
      'achievementStatus': '达成状态',
      'tableIcon': '图标',
      'currentLevelLabel': '当前',
      'levelAchieved': '已达成',
      'levelNotAchieved': '—',
      'writePost': '发帖',
      'postTitle': '标题',
      'postTitleHint': '输入标题',
      'postContent': '内容',
      'postContentHint': '写下你想分享的内容',
      'postSubmit': '发布',
      'postSubmitted': '发布成功！',
      'postSaveFailed': '保存失败，请重试。',
      'postSyncFailed': '无法同步到服务器，请检查网络后刷新。',
      'postEditSuccess': '已更新。',
      'postEditFailed': '更新失败，请重试。',
      'editPost': '编辑帖子',
      'deletePostConfirm': '确定删除此帖？',
      'addPhoto': '添加图片',
      'titleRequired': '请输入标题',
      'contentRequired': '请输入内容',
      'takePhoto': '拍照',
      'pickFromFiles': '从文件选择',
      'maxPhotos': '最多4张',
      'titleMinLength': '标题至少2个字符',
      'contentMinLength': '内容至少10个字符',
      'postCooldown': '3分钟后再发帖',
      'postLink': '链接',
      'postLinkHint': 'https://...',
      'messages': '私信',
      'profileStatFollow': '关注',
      'followScreenTitle': '关注',
      'tabFollowing': '正在关注',
      'tabFollowers': '粉丝',
      'followEmptyFollowing': '还没有关注任何人。',
      'followEmptyFollowers': '还没有粉丝。',
      'followButtonFollow': '关注',
      'followButtonFollowing': '已关注',
      'followUnfollow': '取消关注',
      'loginRequiredForFollow': '请登录后使用关注功能。',
      'networkPageTitle': '{name} 的社交网络',
      'followViewProfile': '查看主页',
      'newMessage': '新私信',
      'noConversations': '暂无对话',
      'noConversationsHint': '给其他会员发私信开始对话吧。',
      'typeMessage': '输入消息内容...',
      'send': '发送',
      'recipientNickname': '收件人昵称',
      'recipientNicknameHint': '输入昵称',
      'freeViewCountLabel': '免费观看次数',
      'sendMessageToUser': '发私信',
      'viewUserPosts': '查看帖子',
      'viewUserComments': '查看评论',
      'activityScore': '活跃度',
      'communityRanking': '社区排名',
      'seeMore': '更多',
      'watchedDramas': '我看过的剧',
      'noWatchedDramas': '还没有观看过的剧',
    },
    'jp': {
      'searchHint': '何でも検索',
      'login': 'ログイン',
      'profile': 'プロフィール',
      'logout': 'ログアウト',
      'logoutSuccess': 'ログアウトしました',
      'settings': '設定',
      'language': '言語',
      'theme': 'テーマ',
      'themeLight': 'ライト',
      'themeDark': 'ダーク',
      'themeSystem': 'システム',
      'notificationSettings': '通知設定',
      'privacyPolicy': 'プライバシー',
      'helpCenter': 'ヘルプ',
      'myPosts': '自分の投稿',
      'myPostBadge': '自分の',
      'myReviews': '私のレビュー',
      'saved': '保存',
      'home': 'ホーム',
      'shorts': 'ショート',
      'popular': '人気',
      'freeBoard': '自由掲示板',
      'questionBoard': '質問掲示板',
      'welcomeLogin': 'DramaHubへ\nようこそ',
      'loginSubtitle': 'メールとパスワードを入力してください',
      'email': 'メール',
      'password': 'パスワード',
      'signUp': '会員登録',
      'noAccount': 'アカウントをお持ちでないですか？',
      'hasAccount': 'すでにアカウントをお持ちですか？',
      'welcomeSignup': 'DramaHubで\nつながろう',
      'signupSubtitle': '選択した言語でアプリが表示されます。同じ言語を選んだユーザーにだけ投稿が表示されます。',
      'country': '国',
      'nickname': 'ニックネーム',
      'nicknameHint': '他のユーザーに表示される名前',
      'passwordConfirm': 'パスワード確認',
      'signUpButton': '登録する',
      'popularPlaceholder': '人気',
      'freeBoardPlaceholder': '自由掲示板',
      'tabHot': '人気',
      'tabGeneral': '一般',
      'tabQnA': 'Q&A',
      'tabReviews': 'レビュー',
      'trendTabHint': 'いいね10以上または閲覧100以上の投稿が表示されます。',
      'reviewsTabEmpty': 'ドラマを検索して最初のレビューを投稿しましょう。',
      'spoilerBadge': 'ネタバレ',
      'reviewSpoilerDisclaimer': 'このレビューにはネタバレが含まれる場合があります。',
      'reviewSpoilerTapToRevealLetterboxd': 'このレビューにはネタバレが含まれる場合があります。タップで表示します。',
      'reviewLikeLabel': 'LIKE?',
      'reviewFilmButton': 'Film >',
      'selectDrama': 'ドラマを検索',
      'reviewDramaSearchHint': 'ショートドラマを検索',
      'ratingLabel': '評価',
      'spoilerToggle': 'ネタバレを含む',
      'reviewNeedDramaRating': 'レビューにはドラマと星評価が必要です。',
      'reviewNeedDrama': 'レビューにはドラマを選択してください。',
      'reviewPleaseSelectRating': '星の評価を選んでください。',
      'search': '検索',
      'searchScopeTitleAndBody': 'タイトル+本文',
      'searchScopeTitle': 'タイトル',
      'searchScopeBody': '本文',
      'searchScopeComment': 'コメント',
      'searchScopeNickname': 'ニックネーム',
      'timeAgoJustNow': 'たった今',
      'timeAgoMinutes': '%d分前',
      'timeAgoHours': '%d時間前',
      'timeAgoDays': '%d日前',
      'timeAgoWeeks': '%d週間前',
      'timeAgoMonths': '%dヶ月前',
      'timeAgoYears': '%d年前',
      'searchCommunityHint': 'タイトル・本文・コメント・ニックネームで検索',
      'searchEnterQuery': '検索語を入力してください',
      'searchNoResults': '"%s"の検索結果はありません',
      'postSoon': '投稿はもうすぐここに表示されます',
      'shortsSoon': 'ショート動画はもうすぐここに表示されます',
      'loginSuccess': 'ログインしました',
      'loginWithGoogle': 'Googleでログイン',
      'loginPreparing': 'ログイン準備中です',
      'signupPreparing': '会員登録ページ準備中です',
      'notReadyYet': '準備中です',
      'enterEmail': 'メールを入力してください',
      'validEmail': '有効なメール形式を入力してください',
      'enterPassword': 'パスワードを入力してください',
      'passwordMin': 'パスワードは8文字以上にしてください',
      'passwordSpecial': 'パスワードに特殊文字を1文字以上含めてください',
      'passwordHint': '8文字以上、特殊文字1文字以上',
      'passwordMismatch': 'パスワードが一致しません',
      'loginErrorWrongPassword': 'パスワードが違います。',
      'loginErrorEmailNotRegistered': 'このメールで登録されたアカウントがありません。',
      'loginErrorGeneric': 'ログインに失敗しました。もう一度お試しください。',
      'enterNickname': 'ニックネームを入力してください',
      'nicknameMin': 'ニックネームは2文字以上にしてください',
      'soon': 'もうすぐ',
      'share': '共有',
      'copyLink': 'リンクをコピー',
      'shareToApps': 'アプリで共有',
      'shareSettings': '共有設定',
      'linkCopied': 'リンクをコピーしました',
      'changeProfilePhoto': 'プロフィール写真を変更',
      'pickFromGallery': 'ギャラリーから選択',
      'removePhoto': '写真を削除',
      'profilePhotoUpdated': 'プロフィール写真を更新しました',
      'profilePhotoPreview': 'プレビュー',
      'edit': '編集',
      'edited': '編集済み',
      'delete': '削除',
      'report': '報告',
      'block': 'ブロック',
      'reportPostTitle': '報告',
      'reportPostMessage': 'この投稿を報告しますか？',
      'reportSubmitted': '報告を受け付けました。',
      'blockPostTitle': '投稿を非表示',
      'blockPostMessage': 'この投稿をフィードから非表示にしますか？',
      'blockPostDone': '投稿を非表示にしました。',
      'save': '保存',
      'done': '完了',
      'rotate': '回転',
      'drama': 'ドラマ',
      'review': 'レビュー',
      'notifications': '通知',
      'notificationsEmpty': '投稿へのコメント・返信・いいねがここに表示されます。',
      'dramaSearchHint': 'ドラマを検索...',
      'popularSearch': '人気の検索',
      'searchResults': '検索結果',
      'rankingEmpty': 'この期間はまだデータがありません。検索やタップでランキングが反映されます。',
      'periodDay': '今日',
      'periodWeek': '今週',
      'periodMonth': '今月',
      'periodYear': '今年',
      'recommended': 'おすすめ',
      'newReleases': '新作',
      'popularRanking': '人気ランキング',
      'category': 'カテゴリ',
      'genre': 'ジャンル',
      'target': '対象',
      'membershipExclusive': '会員限定',
      'dramaExclusive': 'DramaHub 独占',
      'rating': '評価',
      'participants': '参加',
      'ratingsAndComments': '評価・レビュー',
      'writeReview': 'レビューを書く',
      'writeReviewAction': 'レビューを書く >',
      'synopsis': 'あらすじ',
      'episodes': '話数',
      'totalEpisodes': '全%d話',
      'episodeLabel': '第%d話',
      'dramaViewCount': '%s 回視聴',
      'episodeReviewRaterCount': '（%d件の評価）',
      'episodeReviewAlreadyExists': 'この話にはすでにレビューを投稿しています。',
      'episodeReviewSaveFailed': 'レビューを保存できませんでした。もう一度お試しください。',
      'cast': 'キャスト',
      'noCastInfo': '出演情報がありません。',
      'firstReview': '最初のレビューを書いてみましょう！',
      'reviewComposerLikedHint': 'この作品が好き',
      'reviewComposerRepliesHint': '返信を許可',
      'leaveReview': 'レビューを書く',
      'play': '再生',
      'similarDramas': '似た作品',
      'ratingHint': '評価してレビューを書く',
      'ratingInstruction': 'このドラマを評価してください',
      'reviewPlaceholder': 'レビューを書く',
      'reviewTagInputHint': 'タグを追加',
      'reviewPlaceholderLong': 'あらすじ・字幕・吹き替えなどについてのご意見をお聞かせください！',
      'submitReview': '投稿する',
      'submit': '送信',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'loginRequired': 'レビューを書くにはログインしてください',
      'reviewSubmitted': 'レビューを投稿しました！',
      'reviewUpdated': 'レビューを更新しました！',
      'deleteReviewConfirm': 'このレビューを削除しますか？',
      'ratingRequired': '評価を選択してください',
      'reviewMinLength': 'レビューは5文字以上入力してください',
      'joinConversation': 'コメントを追加…',
      'reply': '返信',
      'likes': 'いいね',
      'dislike': '嫌い',
      'comments': 'コメント',
      'sortByTime': '時間順',
      'sortByTop': 'おすすめ順',
      'commentBeFirst': '最初のコメントを書いてみましょう！',
      'commentWrite': 'コメントを書く',
      'writeComment': 'コメントを書く',
      'activityPoint': ' 活動度 +1)',
      'replySubmit': '返信する',
      'filter': 'フィルター',
      'sort': '並び替え',
      'sortByLikes': 'いいね順',
      'sortByLatest': '最新順',
      'contentType': 'コンテンツタイプ',
      'all': 'すべて',
      'interactiveDrama': 'インタラクティブドラマ',
      'shortDrama': 'ショートドラマ',
      'reset': 'リセット',
      'apply': '適用',
      'tags': 'タグ',
      'ageGap': '年齢差',
      'reunion': '再会',
      'loveTriangle': '三角関係',
      'revenge': '復讐',
      'female': '女性',
      'male': '男性',
      'lgbtq': 'LGBTQ',
      'region': '地域',
      'regional': '地域',
      'usa': 'アメリカ',
      'asia': 'アジア',
      'dubbing': '吹き替え',
      'originalAudio': '原音',
      'dubbed': '吹き替え',
      'tooLate': 'もう遅い',
      'lostChild': '迷子',
      'affair': '不倫',
      'friendsToLovers': '友達から恋人へ',
      'harem': 'ハーレム',
      'salvation': '救済',
      'pregnancy': '妊娠',
      'enemyToLover': '敵から恋人へ',
      'destinedLover': '運命の恋人',
      'watchAd': '広告を視聴',
      'watchAdPlusOne': '広告を見て +1回',
      'freeViewCredits': '無料視聴',
      'watchAdToEarn': '広告視聴で無料視聴回数を獲得',
      'noCredits': '無料視聴回数がありません。広告を視聴してください。',
      'level': 'レベル',
      'memberLevel': '会員レベル',
      'points': 'pt',
      'levelInfo': 'レベル情報',
      'levelInfoSubtitle': '活動でポイントを貯めてレベルアップしましょう。',
      'currentLevel': '現在のレベル',
      'totalPointsLabel': '総Point',
      'nextLevelNeeded': '次のレベルまであと N',
      'entireLevelSystem': 'レベルシステム一覧',
      'levelSystemDescription': '各レベルに到達するために必要な累計ポイントです。',
      'attainmentPoint': '達成Point',
      'achievementStatus': '達成状況',
      'tableIcon': 'アイコン',
      'currentLevelLabel': '現在',
      'levelAchieved': '達成',
      'levelNotAchieved': '—',
      'writePost': '投稿する',
      'postTitle': 'タイトル',
      'postTitleHint': 'タイトルを入力',
      'postContent': '本文',
      'postContentHint': '自由に書いてみましょう',
      'postSubmit': '投稿',
      'postSubmitted': '投稿しました！',
      'postSaveFailed': '保存に失敗しました。もう一度お試しください。',
      'postSyncFailed': 'サーバーと同期できませんでした。ネットワーク確認のうえ更新してください。',
      'postEditSuccess': '更新しました。',
      'postEditFailed': '更新に失敗しました。もう一度お試しください。',
      'editPost': '投稿を編集',
      'deletePostConfirm': 'この投稿を削除しますか？',
      'addPhoto': '写真を追加',
      'titleRequired': 'タイトルを入力してください',
      'contentRequired': '内容を入力してください',
      'takePhoto': 'カメラで撮影',
      'pickFromFiles': 'ファイルから選択',
      'maxPhotos': '最大4枚まで',
      'titleMinLength': 'タイトルは2文字以上入力してください',
      'contentMinLength': '内容は10文字以上入力してください',
      'postCooldown': '3分後に再度投稿できます',
      'postLink': 'URL',
      'postLinkHint': 'https://...',
      'messages': 'メッセージ',
      'profileStatFollow': 'フォロー',
      'followScreenTitle': 'フォロー',
      'tabFollowing': 'フォロー中',
      'tabFollowers': 'フォロワー',
      'followEmptyFollowing': 'フォローしているアカウントはまだありません。',
      'followEmptyFollowers': 'フォロワーはまだいません。',
      'followButtonFollow': 'フォロー',
      'followButtonFollowing': 'フォロー中',
      'followUnfollow': 'フォロー解除',
      'loginRequiredForFollow': 'フォロー機能を使うにはログインしてください。',
      'networkPageTitle': '{name}のネットワーク',
      'followViewProfile': 'プロフィールを見る',
      'newMessage': '新規メッセージ',
      'noConversations': '会話はまだありません',
      'noConversationsHint': '会員にメッセージを送って会話を始めましょう。',
      'typeMessage': 'メッセージを入力...',
      'send': '送信',
      'recipientNickname': '宛先ニックネーム',
      'recipientNicknameHint': 'ニックネームを入力',
      'freeViewCountLabel': '無料視聴回数',
      'sendMessageToUser': 'メッセージを送る',
      'viewUserPosts': '投稿を見る',
      'viewUserComments': 'コメントを見る',
      'activityScore': 'ポイント',
      'communityRanking': 'コミュニティランキング',
      'seeMore': 'もっと見る',
      'watchedDramas': '視聴したドラマ',
      'noWatchedDramas': '視聴したドラマはありません',
    },
  };

  String get(String key) => _map[key] ?? key;
}
