// File generated by FlutterFire CLI; 값은 android/app/google-services.json 기준.
// CONFIGURATION_NOT_FOUND 방지를 위해 Firebase 옵션을 명시적으로 사용합니다.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return FirebaseOptions(
      apiKey: 'AIzaSyC34KSKbz8uxt_X3ijCtB0IA-YqGHyxdUY',
      appId: '1:861453767614:android:263e9f1661d0ffc67c1fef',
      messagingSenderId: '861453767614',
      projectId: 'dramahub-22ff2',
      storageBucket: 'dramahub-22ff2.firebasestorage.app',
      authDomain: 'dramahub-22ff2.firebaseapp.com',
    );
  }
}
